### ISSUE TITLE
Images out of order in slider

### ISSUE THREAD

**Issue by awakencompany** [woocommerce/FlexSlider#1014]
Hi - I'm currently using FlexSlider on a custom Shopify store that a fellow creative company and myself are building. Everything is working well as far as design, and the bulk of the functionality.

However - The images are out of order (see here on the homepage: http://four-flours.myshopify.com). I have them in order within the source code like so:
< img src ="slideshow1" >
< img src ="slideshow2" >
< img src ="slideshow3" >
< img src ="slideshow4" >

However, it's outputting them with #4 at the very beginning.

Also, the "randomize" function is NOT turned on. Any ideas what's going on here?
Thanks for any support on this issue.
- Anthony | Awaken Company

**Comment by hbunjes** [comment]
If I only use the second part of @neonics fix (after @@ -889,9 +890,10 @@) it works fine for me.

**Comment by shuvogm** [comment]
This problem still does  exist, in my case last photo coming up at first slide. If I use previous version "2.2.1/jquery.flexslider-min.js" then works alright.
