### ISSUE TITLE
dynamic-carousel-min-max.html missing important instruction

### ISSUE THREAD

**Issue by jesse-bright** [woocommerce/FlexSlider#1123]
The documentation in the demo for ['Carousel with dynamic min/max ranges'](http://flexslider.woothemes.com/dynamic-carousel-min-max.html) is missing:

``` js
start: function(slider){
    flexslider = slider;
}
```

The script that is running on the [demo page](http://flexslider.woothemes.com/dynamic-carousel-min-max.html) includes this required piece of script as seen below:

``` js

    (function() {

      // store the slider in a local variable
      var $window = $(window),
          flexslider;

      // tiny helper function to add breakpoints
      function getGridSize() {
        return (window.innerWidth < 600) ? 2 :
               (window.innerWidth < 900) ? 3 : 4;
      }

      $(function() {
        SyntaxHighlighter.all();
      });

      $window.load(function() {
        $('.flexslider').flexslider({
          animation: "slide",
          animationSpeed: 400,
          animationLoop: false,
          itemWidth: 210,
          itemMargin: 5,
          minItems: getGridSize(), // use function to pull in initial value
          maxItems: getGridSize(), // use function to pull in initial value
          start: function(slider){
            $('body').removeClass('loading');
            flexslider = slider;
          }
        });
      });

      // check grid size on resize event
      $window.resize(function() {
        var gridSize = getGridSize();

        flexslider.vars.minItems = gridSize;
        flexslider.vars.maxItems = gridSize;
      });
    }());
```

However, when omitted throws an error. The documentation doesn't show this piece of the script.
Meaning it is not possible to follow the instructions in the documentation to get this to work . When that bit is left out you get:

```
Uncaught TypeError: Cannot read property 'vars' of undefined 
```

**Comment by AustinGil** [comment]
@jesse-bright, you sir are a saint. Why doesnt the tutorial on the site include this? Thank you!

**Comment by jesse-bright** [comment]
@AustinGil almost two years later! Thank you for confirming this is still required, I wish they'd update their documentation. I'm glad this works for you

**Comment by vyskoczilova** [comment]
The issue is still not resolved.
