### ISSUE TITLE
Orientation change on iOS

### ISSUE THREAD

**Issue by martinstewart** [woocommerce/FlexSlider#1184]
I've noticed some odd behaviour on iOS7.  To replicate the problem:
- in portrait orientation, start on a page with a flexslider
- navigate to another page
- change orientation to landscape
- go back to the first page, staying in landscape orientation

The images within the flexslider are now not displayed correctly. Their width has been retained from the portrait orientation.

![photo 1](https://cloud.githubusercontent.com/assets/8458725/3934922/5d1d71d8-2490-11e4-87ef-feb0432e6205.PNG)

![photo 2](https://cloud.githubusercontent.com/assets/8458725/3934921/5d1cf4d8-2490-11e4-8a7b-d6c57a8804db.PNG)

I can't replicate this on Android devices.

Has anyone a solution to this problem?

Thanks,

Martin

**Comment by seansan** [comment]
Confirmed

**Comment by channabasappa** [comment]
flexslider is not working properly when orientation in ipad from portraits to landscape and vice-varse.

**Comment by jeffikus** [comment]
Hi there - just to clarify, our support policy for iOS is to support the latest version as the adoption rate is extremely high for iOS. Currently version 8 is sitting at 87% adoption rate -> see https://developer.apple.com/support/app-store/ 

If the problem persists on the latest versions of iOS please let us know and we will consider reopening the issue.

**Comment by vlrprbttst** [comment]
@jeffikus i always had this problem with flexslider. i just used on another project and this is still happening, im on flexslider jQuery FlexSlider v2.6.3 on the latest iOS. is there a workaround?

**Comment by jeffikus** [comment]
Have reopened as part of 2.7.0

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
