### ISSUE TITLE
direction nav buttons not over slideshow (with fixed code)

### ISSUE THREAD

**Issue by czirkoszoltan** [woocommerce/FlexSlider#1247]
when there are a lot of thumbnails, the direction buttons (prev/next) usually float somewhere between the image slideshow and the thumbnails.
this is because

<div class="flexslider">

<div class="flex-viewport">
   images ...
</div>

<div class="flex-direction-nav">
   next/prev buttons
</div>

<div class="flex-thumbnails">
  images ...
</div>

</div>

so the direction nav is not INSIDE the viewport, but it is positioned top: 50%.

this can be fixed by adding the flex-direction-nav to the viewport, and not to the flexslider container itself.

the fix is:

```
  directionNav: {
    setup: function() {
      var directionNavScaffold = $('<ul class="' + namespace + 'direction-nav"><li><a class="' + namespace + 'prev" href="#">' + slider.vars.prevText + '</a></li><li><a class="' + namespace + 'next" href="#">' + slider.vars.nextText + '</a></li></ul>');

      // CONTROLSCONTAINER:
      if (slider.controlsContainer) {
        $(slider.controlsContainer).append(directionNavScaffold);
        slider.directionNav = $('.' + namespace + 'direction-nav li a', slider.controlsContainer);
      } else {
        slider.viewport.append(directionNavScaffold);   // instead of slider.append
        slider.directionNav = $('.' + namespace + 'direction-nav li a', slider.viewport);   // instead of slider
      }
```

**Comment by czirkoszoltan** [comment]
Important: the fix will only work if there is a viewport, which is not true if the animation is of the type "fade". Better solution:

          // CONTROLSCONTAINER:
          if (slider.controlsContainer) {
            $(slider.controlsContainer).append(directionNavScaffold);
            slider.directionNav = $('.' + namespace + 'direction-nav li a', slider.controlsContainer);
          } else {
            var appendDirectionNavTo = slider.viewport || slider;
            appendDirectionNavTo.append(directionNavScaffold);
            slider.directionNav = $('.' + namespace + 'direction-nav li a', appendDirectionNavTo);
          }

**Comment by samowitsch** [comment]
It would be nice to have a option for that. I have the same problem here. flex-direction-nav over flex-control-thumbs would be really helpful to simplify styling.
