### ISSUE TITLE
Swiping on iPhone causes slideshow to stop playing

### ISSUE THREAD

**Issue by estockwellalpert** [woocommerce/FlexSlider#1249]
I'm not sure if this issue has been addressed already, but I noticed that when I swipe to the next slide on an iPhone, the slideshow stops playing. I can continue to swipe to the next slide manually, but it no longer plays on its own. Furthermore, the slideshow stops playing any time I touch the image, regardless of whether I actually swipe or not. Is there a setting I need to add to make it keep playing after being touched?

**Comment by cvn** [comment]
Try setting [pauseOnAction](https://github.com/woothemes/FlexSlider/wiki/FlexSlider-Properties#pauseonaction) to false.

    $('.flexslider').flexslider({
      pauseOnAction: false
    });

If that doesn't resolve it, you may also want to try setting pauseOnHover to false, since iOS can interpret taps as hover events.
