### ISSUE TITLE
Jetpack Infinite Scroll Not Loading Flexslider

### ISSUE THREAD

**Issue by jamigibbs** [woocommerce/FlexSlider#1254]
I'm not sure if this is a Jetpack issue or Flexslider but when loading new posts with the Infinite Scroll feature, the slider isn't firing.

**Comment by mattyza** [comment]
Hi @jamigibbs. :)

That sounds, to me, like something which may require an event to fire on `post-load`, an event fired by infinite scroll in Jetpack.

To clarify, are you referring to a slider within the new posts being loaded?

For reference, I'm including the Jetpack infinite scroll documentation here: http://jetpack.me/support/infinite-scroll/

**Comment by jeffikus** [comment]
Hi @jamigibbs can you provide me with a live url of what you are experiencing please? Thanks, Jeff

**Comment by jamigibbs** [comment]
The first post listed on [this page](http://demo.rescuethemes.com/merch/blog/) (Gallery Post Example) is a gallery/slider post that's loading before infinite scroll and all is well here.

But scrolling down to the second example called "Another Gallery Post Example" on that same page will show infinite scroll displaying the post but images not displaying. The slider does appear when accessing [page two](http://demo.rescuethemes.com/merch/blog/page/2/) of the blog list though.
