### ISSUE TITLE
Load different images depending on screen width

### ISSUE THREAD

**Issue by celestial** [woocommerce/FlexSlider#1260]
I am using flexslider with large 1920x1028 images and would like to use smaller square images on mobile devices. Is there a way to load different images depending on screen width? I have been trying to set it up using Foundation Interchange. Interchange works fine for static images, but the flexslider javascript is not loading with Interchange. 

Any recommendations for how to get the slider working with interchange, or any other way to accomplish this? I would also consider loading a static image below 640px, and have the slider kick in above 640.

Thanks for help,
Celeste

**Comment by Murando** [comment]
No solution for that? Due to Google´s efforts in mobile friendliness large images on mobile are considered as critical error and the pages will not be included in search results of mobile devices.

**Comment by bram1028** [comment]
I'm using CSS `background-image` on the `li` tags instead of `img` tags, so my plan for this is to use CSS media queries to load optimized images. I don't know if that'll help you.
