### ISSUE TITLE
Flexslider 2 infinite slide loop

### ISSUE THREAD

**Issue by 01Kuzma** [woocommerce/FlexSlider#1265]
Hi!
The main task is to force flexslider 2 to work as follow:

1). The slider displays 3 items per page. (Done)

2). Press the next arrow (or previous) and reach the end. Once the end of slides is reached the slideshow should continue as infinite loop. Now once the end is reached slider just skips to first slide this is wrong for me.

The configuration is:

(function($) {
    $(function() {
        $(window).load(function() {
          $('.flexslider').flexslider({
            animation: "slide",
            slideshow: false,
            animationLoop: true,  
            touch: true, 
            reverse: false,
            itemWidth: 398,  
            itemMargin: 0,
            minItems: 3,
            maxItems: 3
          });
        });
    });
})(jQuery);

Removing the itemWidth: 398, solves the infinite loop issue but only one item per page is displayed. Waiting for reply!

**Comment by yoyos** [comment]
I upvote this.

There should be a new option called infinite: true

If false, the carousel rewind to the first slide, if true, tu carousel continue like if the first slide was the next one.

**Comment by hellboy81** [comment]
Is this feature request still active?

**Comment by yoyos** [comment]
What do you mean by active ? The feature is still needed but the request is sleeping, not very active :p

**Comment by jeffikus** [comment]
Thanks for the feedback, if you guys have a working solution, submit a pull request and I'll happily review it. But not going to build this in right now.
