### ISSUE TITLE
Cannot programmatically go straight to last slide

### ISSUE THREAD

**Issue by frob** [woocommerce/FlexSlider#1273]
I have put it into this jsfiddle
http://jsfiddle.net/Ls3c816u/3/

If you click on "go to last slide" nothing happens
If you click on "go to second to last slide" then it goes to the second to last slide
If you click on "go to last slide" after clicking on "go to second to last slide" then it will go to the last slide.

**Comment by frob** [comment]
Looking after doing some tests the problem looks like it is in the canAdvance method. 

If using .flexAnimate directly and bypassing the .flexslider helper function you can pass true to the override parameter and force the animation.

**Comment by frob** [comment]
Did anything happen here?

**Comment by jeffikus** [comment]
@frob I'll look into this following the 2.6.0 release cycle which I'm currently busy with. thanks!

**Comment by frob** [comment]
So why was this labeled as 'wontfix'

**Comment by jeffikus** [comment]
@frob your jsfiddle seems to work, not sure if there's anything else to be done here?

**Comment by frob** [comment]
Okay, thanks for testing. 

It does look as though as of the current release 2.7.0 this has been fixed.
