### ISSUE TITLE
Slider miscalculating "visible" slides

### ISSUE THREAD

**Issue by aghouseh** [woocommerce/FlexSlider#1294]
It's miscalculating how many slides are "visible" and causing the second-to-last slide to slide directly to the end, effectively moving 2 instead of 1. Also, this results in miscalculated paging items, when that is used. I've boiled it down into a very basic reproducible codepen.

http://codepen.io/aghouseh/pen/pvqNjG
https://gist.github.com/anonymous/85623a1eab990864cc38

**Comment by flebas** [comment]
I think that correct visible calculation is : 
 slider.visible = Math.floor((slider.w +  slideMargin)/(slider.itemT));
