### ISSUE TITLE
Data Attributes

### ISSUE THREAD

**Issue by JoeHana** [woocommerce/FlexSlider#1303]
I believe there was a (native) way to pass data-attributes to the slider. But for some reason that don't work anymore and I couldn't find any references. So my question is: Does the slider also work with data-attributes? If so, how? If not, why? :)

Thanks in advance

**Comment by alexplusde** [comment]
+1

**Comment by jeffikus** [comment]
Please provide an example of what you are struggling with, either code or URL. I need some more context here to answer best.
