### ISSUE TITLE
Previous navigation arrow not shown in android native brauser

### ISSUE THREAD

**Issue by erkidorbek** [woocommerce/FlexSlider#1304]
"Previous" navigation arrow not shown in android native brauser ("next" is shown).
The problem even existed on slider demo pages. Works fine with chrome tho.

Tablet model: MediaPad 7 Youth 2
Android version 4.3

**Comment by PurpleTT** [comment]
I also have this problem on the default android browser.

It is for galaxy s2-s5 some notes and tablets.

It is actually the f001 font, which is the left/previous arrow.

For some reason the android browser cannot read it.

Is there a fix to this yet?

**Comment by erkidorbek** [comment]
I just replaced fonts for images in my project. Sadly didn't find out what caused the error.
