### ISSUE TITLE
Any way to speed up initial "smoothHeight" animation?

### ISSUE THREAD

**Issue by syntax53** [woocommerce/FlexSlider#1306]
I like the smooth height option as it eliminates the gap between slides and their images+caption text.  However, I don't like how when the page initially loads there is an animation when drawing the slider.  On some browsers it seems to start very large and the content beneath slides up (IE) and then on other browsers the size starts at 0 and the content slides down (iPad iOS).  Ideally it would not slide at all, but if it has to due to technical reasons I would rather it just snap into place.  Site: http://www.abington.k12.pa.us/

Thanks

**Comment by tillyt** [comment]
was investigating this myself, line 792 of jquery.flexslider.js, it calls the smoothHeight method with the animationSpeed as argument, so pass in a different number

default is:    ` animationSpeed: 600,            //Integer: Set the speed of animations, in milliseconds`

Ideally I want to avoid the smoothHeight altogether and just have the slider vertically centered in some container but I can't figure that out so for now I just changed the animation speed
