### ISSUE TITLE
Option for "fade" not to fade out previous slide till next slide is fully opaque

### ISSUE THREAD

**Issue by jsit** [woocommerce/FlexSlider#1308]

**Comment by MaggieRezo** [comment]
This works fantastic, I don't know why it wasn't merged to the project?

**Comment by jeffikus** [comment]
Will take a look at this in the next milestone.

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.

**Comment by jsit** [comment]
Is this an option now, or is it just turned off? Seems like it might be useful in some cases to have it fade, but not in others.

**Comment by jeffikus** [comment]
@jsit we're not going to modify the fade behavior at this time.
