### ISSUE TITLE
Wrong slide in viewport in IE and Firefox

### ISSUE THREAD

**Issue by robskidmore** [woocommerce/FlexSlider#1311]
The slider is rendering with a cloned slide in the viewport rather than the correct active slide. I'm using the latest version 2.4.0.

``` html
<li class="clone"></li><!-- slider renders with this slide in viewport -->
<li class="flex-active-slide"></li><!-- when it should be this one -->
<li class="clone"></li>
```

For some reason even though the slides are all floated left in FF and IE the first slide does not move all the way over to the left.

Any thoughts?

**Comment by robskidmore** [comment]
This is a complete hack but it solves the problem. If i set the first cloned slides to `position: absolute` it takes care of the issue.

I'll leave this here in case someone has a similar problem.

**Comment by robskidmore** [comment]
Never mind. The Hack broke all the things in Chrome. Back to square one.

**Comment by robskidmore** [comment]
New hack. Added this as a callback so it's only applied to non-webkit browsers.
```javascript
start: function() {
    if(!jQuery.browser.webkit) {
        jQuery(".slides .clone:first-child").css("position", "absolute");
    }
}
```

**Comment by jeffikus** [comment]
Is this only happening on your site or on our demo as well?

**Comment by robskidmore** [comment]
Only on my site. Guess I probably should have checked that before opening an issue.

**Comment by jeffikus** [comment]
Any custom JS loaded on your end?
