### ISSUE TITLE
FlexSlider 2.4 not compatible with jQuery 1.11.2

### ISSUE THREAD

**Issue by SimonFricker** [woocommerce/FlexSlider#1332]
FlexSlider 2.4 not compatible with jQuery 1.11.2 and thus it is no longer compatible with WordPress. 

https://jsfiddle.net/t7egf690/6/

**Comment by jeffikus** [comment]
Hi there

The slides are definitely there - you can inspect the markup, have you tried this locally and not using jsfiddle? Also have you tested with 2.5.0 that was release last week Friday?

Thanks,
