### ISSUE TITLE
Carousel. Bootstrap-3.3.4 

### ISSUE THREAD

**Issue by floatingpenguin** [woocommerce/FlexSlider#1333]
How can I set a minimum and maximum image size when the carousel is displayed in a big monitor or a small smartphone?

The default setting deform the image to 100%, it doesn't matter how big or small it is. 

Thank you :D

**Comment by jeffikus** [comment]
Hi there

You can apply CSS to the container divs to limit the height and width. I'm not sure of the context that you mention, but you can even use min-width and max-width etc (and the sam for height)

If you are using % based widths and heights I'm assuming you are catering for responsive design, however you could even use media queries to handle specific breakpoints.  

Let me know if that doesn't make sense to you!

**Comment by floatingpenguin** [comment]
Hello Jeffrey,

Thank you for taking your time in replying my message.

I am on my early days learning by myself responsive coding to make my web
responsive.

I managed to fix the img to a max-width and min-width, I don't know if it's
right but it does help and the image doesn't shrink.

*bootstrap.min.css*

.carousel-inner>.item>a>img,.carousel-inner>.item>img,.img-responsive,.thumbnail
a>img,.thumbnail>img{display:block;*max-width:1920*;height:auto;
*min-width:320*}


I still have a few problems to solve, see attached images.

1.-  Image 1

   - The image stretches in a 27 inch monitor (it should be displayed up to
   its real size 1920px, in the middle of the screen).

2.- Image 2

   - How could I place the carousel just after the navbar without extra
   space?
   - I would prefer the image centred on the carousel rather than starting
   the display from the left hand side.
   - How can I put back to place the 'three little dots' under the button?

4.- Image 3 (Sorry this one doesn't affect the carousel)

   - Is it any way to write a long title on the navbar without make a real
   mess on small devices?

I hope they're not too many questions.

By the way, here is the test folder
<http://floatingpenguin.co.uk/test/index.html> which contains the files.

Thank you for your time Jeffrey, it's much appreciated.

Regards,
Inma Sanchez


Inma Sanchez
+44 771 940 1378 (Mobile) | inma@floatingpenguin.co.uk
*Floating Penguin* | Spanish Translation Services | floatingpenguin.co.uk

<http://floatingpenguin.co.uk/>

<admin@floatingpenguin.co.uk>
<http://floatingpenguin.co.uk/img/facebook.png>
<https://plus.google.com/108625091003470909594/posts>
<https://www.linkedin.com/company/floating-penguin>
<https://twitter.com/aspanishpenguin>
<https://www.pinterest.com/floatingpenguin/pins/>

**Comment by jeffikus** [comment]
@floatingpenguin this is the best place for us to communicate, unless it is a private project that you aren't allowed to link to because of something like an NDA.

**Comment by floatingpenguin** [comment]
Hello Jeffrey,

I managed to fix the img to a max-width and min-width and the image doesn't
shrink any more

*bootstrap.min.css*

.carousel-inner>.item>a>img,.carousel-inner>.item>img,.img-responsive,.thumbnail
a>img,.thumbnail>img{display:block;*max-width:1920*;height:auto;
*min-width:320*}


I still have a few problems to solve:

   - The image stretches in a 27 inch monitor. It should be displayed up to
   its size 1920px.
   - How could I place the carousel just after the navbar without extra
   space?
   - I would prefer the image centred on the carousel rather than starting
   the display from the left hand side.

Thank you for your time Jeffrey, it's much appreciated.

Regards,
IS
