### ISSUE TITLE
Manually define strength of swipe

### ISSUE THREAD

**Issue by ThekhoN** [woocommerce/FlexSlider#1347]
Is there a way to define the "swipe" strength when using flexslider for touch based devices?
I would like to increase the "swipe" threshold of the slider.
I am using the slider as a content slider in mobile device.

As mentioned,  I am using Flexslider as a content slider and not as a single image slider, and my content has variable height. So, when i scroll/swipe down, the next/prev easily gets initiated, which gives a very annoying and erratic experience. If I am not wrong, this could be prevented if we increase the swipe threshold.. Is this possible?

```
    var $flexslider = $('.flexslider');
    $flexslider.flexslider({
            animation: "fade",
            manualControls: ".flex-control-nav li",
            useCSS: true /* Chrome fix*/,
            slideshow:false,
            smoothHeight:true,
            animationLoop:false,
            touch:true,
            directionNav:false 
});
```

**Comment by jeffikus** [comment]
Hi there

The short answer is, at the moment no. But, I am planning on looking into overhauling the mobile touch events. It's just a question of prioritizing issues at the moment. If you have a suggestion I would love to check out what you can come up with via a pull request :) I'd be more than happy to review the code and merge it if it makes sense for the project.

Thanks!
