### ISSUE TITLE
Calling play() on a playing slider causes it to pause.

### ISSUE THREAD

**Issue by jono-hayward** [woocommerce/FlexSlider#1349]
I've noticed that if I manually call `play()` on a currently-playing instance of FlexSlider, it causes the slider to pause.

This appears to be happening on lines 824-825 of jquery.flexslider.js:

``` javascript
slider.play = function() {
    if (slider.playing) { clearInterval(slider.animatedSlides); }
```

 in which the playback interval is cleared when `play()` is called and `slider.playing` is true.

This has the effect of pausing the slider, though in this case `slider.playing` still returns true, and the slider still thinks it's playing. The only way around this (externally at least) is to call `pause()` followed by `play()` again.

**Comment by jeffikus** [comment]
hi there, can you provide a bigger context for me? like a gist or something of your code where you are doing this. Also the version of flexslider that you are using.

Thanks,

**Comment by jono-hayward** [comment]
Sure!

I'm using FlexSlider v2.2.2, but the code that I referenced in my previous post is still present in the latest version of the repo.

Markup:
```
<section class="slider">
	<div class="slides">
		<article>[content]</article>
		[...]
	</div>
	<div class="slider-nav"></div>
</section>
```

And here's the code I'm using to instantiate flexslider:

```javascript
$(window).load(function() {

	fslider.flexslider({
		selector: '.slides article',
		animation: 'slide',
		useCSS: true,
		animationLoop: true,
		startAt: 0,
		allowOneSlide: false,

		slideshow: true,
		slideshowSpeed: 4500,
		animationSpeed: 1200,
		initDelay: 0,

		pauseOnAction: true,
		pauseOnHover: false,

		controlNav: true,
		controlsContainer: ".slider-nav",
		directionNav: true,
		prevText: 'Previous',
		nextText: 'Next',

		start: function(slider) {

			$(window).on('scroll touchmove', function(e) {
					
				if(slider.isInView()) {
					slider.play();
				} else {
					slider.pause();
				}

			});

		}
	});
});
```

**Comment by jeffikus** [comment]
Hi again, have you tried with the latest version - 2.5.0?
