### ISSUE TITLE
Swipe on thumbnail slider causes animation on main slider

### ISSUE THREAD

**Issue by mtwords** [woocommerce/FlexSlider#1352]
Hi,

I'm using a main slider combined with a thumbnail slider likely as shown in the demo: http://flexslider.woothemes.com/thumbnail-slider.html

On mobile devices, when I swipe on the thumbnail slider, the main slider is animated as well. It seems that every time a "select" event is fired on the image the swipe has started from. This looks strange, because the thumbnail slider and the main slider are animating synchronously. Is there a way to prevent this behavior?

This can be reproduced on the mentioned demo site.

Regards

**Comment by awilliams219** [comment]
Also having this problem.

**Comment by ianhernandez** [comment]
Hate to bring up an old issue, but looking for a little bit of insight on dealing with this issue.
