### ISSUE TITLE
customDirectionNav doesn't work if directionNav is false

### ISSUE THREAD

**Issue by dpedu** [woocommerce/FlexSlider#1359]
Use case: using a custom direction nav and wanting to prevent the default one from being created.

When creating my my slider I'm setting: `directionNav: false` and `customDirectionNav` to a jQuery object pointing at identical markup to what the default directionNav creates, within some wrapping stuff. No event listeners are added to the custom direction nav when directionNav is false.

**Comment by brothatru** [comment]
directionNav must be set to true in order for customDirectionNav to work. I believe when customDirectionNav is set, it overwrites the default directionNav buttons.
