### ISSUE TITLE
Flexslider caption delay before showing

### ISSUE THREAD

**Issue by thehung2224** [woocommerce/FlexSlider#1360]
Hi,

When I have flexslider set to "Slide' it starts animating but I am having issues with the caption. When I select new slide, it takes over 30 seconds before showing the caption, then it runs fine.

I dont' know what to do to fix this, please help

https://jsfiddle.net/v21k3q7b/3/

Best Regards,
Hung The.

**Comment by anand81192** [comment]
Hi,
     Here is a small trick. Remove position property from .flex-caption class and use margin for positioning
