### ISSUE TITLE
Loading flexslider issue

### ISSUE THREAD

**Issue by PabloArty** [woocommerce/FlexSlider#1362]
Hello! I'm doing a site about shoes, when you click a show you open a lightbox with the flexslider inside, but when the lightbox come up the slider doesn't render.

![captura de pantalla 2015-06-25 a las 12 12 54](https://cloud.githubusercontent.com/assets/6517199/8360642/a272add0-1b33-11e5-919c-e75d92505e6e.png)

But when i resize the window then the slider appears!

![captura de pantalla 2015-06-25 a las 12 13 06](https://cloud.githubusercontent.com/assets/6517199/8360654/b2c395fa-1b33-11e5-93bd-c93a94b1bd9a.png)

I'm using a slider with carrousel:

  $(function(){
      SyntaxHighlighter.all();
    });
    $(window).load(function(){
      $('#carousel').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 250,
        itemMargin: 5,
        asNavFor: '#slider'
      });
      $('#slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        sync: "#carousel",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
    });

I suppose that I need to reload the slider every time that I click a Shoe but I don't know how to do it.

**Comment by AnastasiaVays** [comment]
I believe I have a similar issue - http://sc.com.ly/show/mw1MSBZpI4lC7UVq9esOcJtQH5h3kTXo. I've checked almost all open issues related....specially with WP...Any solution to that?
