### ISSUE TITLE
navbar rewind not working

### ISSUE THREAD

**Issue by telemarker** [woocommerce/FlexSlider#1363]
hey jeffikus,

i use flexslider with a navbar where you can navigate with thumbs in a carousel.
i just found out that the carousel rewinds itself too late (about 3 pictures)
you can check out this issue on this site:
http://framegrabber-medien.com/portfolios/touristeninformation-iphofen/
best regards
telemarker

**Comment by telemarker** [comment]
any news on this?

**Comment by jeffikus** [comment]
Please update to 2.5.0 and let me know if the issue persists https://github.com/woothemes/FlexSlider/releases/latest
