### ISSUE TITLE
Slideshow set to true together with Sync breaks the plugin

### ISSUE THREAD

**Issue by yanodnoralov** [woocommerce/FlexSlider#1367]
When you have two sliders on one page and have them synced to one another AND have "Slideshow" set to true, the plugin breaks with the following error:

TypeError: t is undefined
....pauseOnAction,!1,!0);break;case"play":t.playing||t.asNav||t.play();break;case"p...
TypeError: t is undefined
...=a.animatingTo;switch(e){case"animate":t.flexAnimate(n,a.vars.pauseOnAction,!1,!...
TypeError: t is undefined
....pauseOnAction,!1,!0);break;case"play":t.playing||t.asNav||t.play();break;case"p...

Any ideas of why these two simple functions together break the plugin and what a possible solution could be?

**Comment by yanodnoralov** [comment]
If anyone can provide a solution, I would love to pay you!

**Comment by jeffikus** [comment]
hi there @yanodnoralov - can you post your full code here so the community can take a look?

**Comment by yanodnoralov** [comment]
Sure. 

<div id="flexslider1" class="flexslider">
		  <ul class="slides">
		    <li>
		      <img src="slide1.jpg" />
		    </li>
		    <li>
		      <img src="slide2.jpg" />
		    </li>
		    <li>
		      <img src="slide3.jpg" />
		    </li>
		  </ul>
		</div>
		
		<div id="flexslider2" class="flexslider">
		  <ul class="slides">
		    <li>
		      swimming
		    </li>
		    <li>
		      bus feet
		    </li>
		    <li>
		      bench
		    </li>
		  </ul>
		</div>
		
		<div class="controls">
		    <li>
		      <div class="nav-icon"></div>
		    </li>
		    <li>
		      <div class="nav-icon"></div>
		    </li>
		    <li>
		      <div class="nav-icon"></div>
		    </li>
		</div>


$(document).ready(function() {
  $('#flexslider1').flexslider({
    manualControls: ".nav-icon",
    animation: "fade",
    directionNav: false,
    slideshow: true,
    sync: "#flexslider2"
  });
  $('#flexslider2').flexslider({
    animation: "fade",
    directionNav: false,
    controlNav: false,
    slideshow: true
  });
});
