### ISSUE TITLE
It doesn't work on defer, while all other js working fine.

### ISSUE THREAD

**Issue by vinodpareek** [woocommerce/FlexSlider#1369]
Hi

<script defer="defer" type="text/javascript" src="assets/flexslider/jquery.flexslider-min.js" ></script>

doesn't work.

How to solve it, if I want to defer flexslider js

**Comment by vinodpareek** [comment]
any solutions for it.

**Comment by jeffikus** [comment]
Hi there, please provide some context - I have no idea what you are trying to do.
