### ISSUE TITLE
Flexslider with LazyLoad : Bug with IE11

### ISSUE THREAD

**Issue by Eric007BK** [woocommerce/FlexSlider#1384]
Hi

When i use Flexslider with Lazyload, i have a big "blank aera" under the slider until all the pictures are loaded.

This is an example.
http://codepen.io/Eric007BK/pen/WvybZE

Best regards

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
