### ISSUE TITLE
Problem with the second image is already in view with the first image

### ISSUE THREAD

**Issue by ilumticsd** [woocommerce/FlexSlider#1391]
Hi all,
I have that problem too, see how the second image is already in view with the first image. As soon as you resize the browser, it snaps into place and fixes it.
I tried to fix, but can’t seem to figure out why it’s doing this. I updated to 2.5 flex slider, but that didn’t help.

http://cl.ly/image/3X303O0J2H3i/o
first load with this: transform: translate3d(-555 ..

but this is correct : http://cl.ly/image/0P2O1K3j263l
transforom: translate3d(-472 ..

I'm appreciated if any one have solution ?

**Comment by jeffikus** [comment]
Hi there

Thanks for reporting, can you confirm this is occuring with another theme as well? Like Twenty Fifteen or Fourteen?

**Comment by ilumticsd** [comment]
Sorry this just a static HTML template, not a wp theme

**Comment by jeffikus** [comment]
Ok sure, any chance you can make the full code available for me to test with?

**Comment by ilumticsd** [comment]
This is HTML code:
<div class="flexslider flexsliderPro flexslider-sidenav">
												<ul class="slides">
													<li data-thumb="images/products/product-9.jpg">
														<a class="popup-img" title="The Product 1" href="images/products/product-9.jpg"><img src="images/products/product-9.jpg" alt=""></a>
													</li>
													<li data-thumb="images/products/product-8.jpg">
														<a class="popup-img" title="The Product 2" href="images/products/product-8.jpg"><img src="images/products/product-8.jpg" alt=""></a>
													</li>
													<li data-thumb="images/products/product-7.jpg">
														<a class="popup-img" title="The Product 3" href="images/products/product-7.jpg"><img src="images/products/product-7.jpg" alt=""></a>
													</li>
													<li data-thumb="images/products/product-6.jpg">
														<a class="popup-img" title="The Product 4" href="images/products/product-6.jpg"><img src="images/products/product-6.jpg" alt=""></a>
													</li>
												</ul>
											</div>

And js:
$('.flexsliderPro').flexslider({
		animation: "slide",
		controlNav: "thumbnails",
		smoothHeight: true,
		slideshow: false,
		directionNav: false
	});

or you can take a look at live demo here:
http://pixelgeeklab.com/html/marvel/shop-product-detail-fullwidth.html

Thanks very much for your help :-)

**Comment by ilumticsd** [comment]
Hi jeffikus,
Can you please help me with that? 
Thanks and look forward to hearing from you soon.

**Comment by jeffikus** [comment]
Hi @ilumticsd just backlogged at the moment, will review as soon as I have time.

**Comment by ConquerorsHaki** [comment]
I have the same problem but on the left side.

http://vfrbb.de/vfr/content/tabellenf%C3%BChrung-verteidigt
