### ISSUE TITLE
Swipe - slide not working in FireFox 39

### ISSUE THREAD

**Issue by hatsforbats** [woocommerce/FlexSlider#1395]
First off, I love the flexslider, thanks!

Now, I have a Windows 8 touch screen laptop and swiping to navigate doesn't work in FireFox 39.0 but does work in IE11 and Chrome.

I am pretty sure it's not in my code implantation because it doesn't work on the demos page either: http://flexslider.woothemes.com/basic-slider-with-caption.html

Is this a known issue?

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
