### ISSUE TITLE
Initial slide load portion of 2nd slide visible

### ISSUE THREAD

**Issue by Clearnine** [woocommerce/FlexSlider#1403]
On initial load a portion of the 2nd slide is visible.  If the slide is advanced or the browser resized it corrects it.  Subsequent slides, and the first slide are correct when they appear.  For example:

![screen shot 2015-08-03 at 9 59 07 am](https://cloud.githubusercontent.com/assets/3318904/9042883/6eff1090-39c6-11e5-86eb-577b357da35a.png)

**Comment by thykos** [comment]
I have same problem=( Who know how to fix this?

**Comment by jeffikus** [comment]
Hi there. Please provide a url for me to test on. Thanks.
