### ISSUE TITLE
Destroy an instance?

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [woocommerce/FlexSlider#1406]
I see that the .destroy method has been pushed back until 2.6.0, so how can I disable Flexslider in the meantime, when the user resizes their window?

I've tried a little hack using jQuery's .remove() and then .prepend() on resize, but it didn't work properly. What else can I do?

**Comment by anthonycollini** [comment]
+1, this has been in development for years, with actual pull requests. It's a little ridiculous this method hasn't been included.

**Comment by jeffikus** [comment]
@anthonycollini I can't speak on previous years, but it is scheduled for 2.6.0 - I will be picking up that milestone at the end of next week.

**Comment by ruant** [comment]
Was this added with the 2.6 release that just came out?

**Comment by jeffikus** [comment]
@ruant not in 2.6.0 as it was secondary focus, but is the primary focus for 2.7.0 - you can see the milestone issues here -> https://github.com/woothemes/FlexSlider/milestones/2.7.0

**Comment by ruant** [comment]
@jeffikus Perfect! Keep up the good work! :+1:

**Comment by jeffikus** [comment]
@ruant I really appreciate the kind words, it makes a big difference to hear that from people like you in the community!

**Comment by jeffikus** [comment]
Just updated this to be in the right milestone - 2.6.1 going out this week, 2.7.0 continues.

**Comment by lanewinfield** [comment]
Did this make it in the 2.6.1 release?

**Comment by jeffikus** [comment]
@lanewinfield no, i updated the milestone to reflect that.

**Comment by ahoebeke** [comment]
News on this?

**Comment by alexplusde** [comment]
👎 this has been asked for so many times on github and stackoverflow. I really love flexslider, but this one is a show stopper.

**Comment by curiouscrusher** [comment]
Been almost 2 years since this feature was "started". Any chance it's still in the works, or has it just been dropped?
