### ISSUE TITLE
percentage on viewport shows multiple images on first load

### ISSUE THREAD

**Issue by jesspritchard** [woocommerce/FlexSlider#1407]
Hi,

I am using FlexSlider v2.3.0 with thumbnails activated for the Control Nav.

In the CSS I have:

.flex-viewport { width: 75%}
.flex-control-thumbs { width: 24%}

On initial load however the flexslider shows part of one image and part of the next. I've determined it has something to do with the 75% width - when I change it to either 50% or 100% it works fine.

Is there a way to have a 75% viewport?

Thanks,
Jess

**Comment by jessirwin** [comment]
Has anyone had a chance to look at this?

**Comment by jeffikus** [comment]
Hi Jess, do you have a live url I can take a look at? Thanks,
