### ISSUE TITLE
problem with safari

### ISSUE THREAD

**Issue by lironrichkid** [woocommerce/FlexSlider#1409]
I have problem in this page on safari:
http://www.gnr.co.il/he/catalog/a/item/?ItemID=368

when change between images the transform isnt with animation.
this is the function that is called whenever click on a color button to change the product image (moves to another slide):
    function moveToSlide(index, count) {
        $('#makat').flexslider(index);
    }
(makat is my slider id)
in chrome it works pretty good.

thanks.

**Comment by lironrichkid** [comment]
???

**Comment by jeffikus** [comment]
@lironrichkid not sure what the ??? comment is about, but please be patient while this is looked at.
