### ISSUE TITLE
Navigation buttons not working when clicked on certain hardware with Chrome 

### ISSUE THREAD

**Issue by IanGrainger** [woocommerce/FlexSlider#1418]
We have a customer who just bought the Acer Z3-615 - and the navigation arrows of Flexslider v2.1 aren't working for them in Chrome 44.0.2403.157. They work in IE and they work on all the hardware I've been able to find.

Does anyone else know about this issue? It sounds pretty similar to one a few years ago that turned out to be driver related and was fixed in a later version of Chrome.

**Comment by noahkuhn** [comment]
Hey Ian, is it a touch screen...

https://github.com/woothemes/FlexSlider/issues/351

**Comment by IanGrainger** [comment]
No.
