### ISSUE TITLE
first slide not sliding in but appearing "in place" when clicking ">" on last slide

### ISSUE THREAD

**Issue by zakomat** [woocommerce/FlexSlider#1420]
hi flexslider enthusiasts,

i have been trying to fix this problem for many hours now but am quite a newbie and cannot fix it.

i have a flexslider with images and text divs on slide 1.
animation : "slide" 
when it is on the last slide and i click the next ">" button once more, the text div on slide 1 slides in properly from the left but the image is not visible.
when the slide transition is finished the image suddenly pops in in place.

i did not find anyone else resp. a thread discussing this.
the problem persists whatever version of flexslider i use.

do you have any appreciated tip?

![image](https://cloud.githubusercontent.com/assets/14169822/9723676/f0c3b182-55c6-11e5-95c7-16519c53c929.png)

thank you very very much for any tips!
steve.

**Comment by jeffikus** [comment]
Hi there, can you provide a live url that I can test it on for context? Thanks,

**Comment by Antoxa258** [comment]
Same problem.
