### ISSUE TITLE
Nav's sub menu disappears when mousing to it because of Flexslider behind.

### ISSUE THREAD

**Issue by BenRacicot** [woocommerce/FlexSlider#1422]
I have a main website navigation in its typical placement, top nav.
When scrolling over an item with sub items the sub ul appears, however once scrolling to these sub items they disappear because Flexslider is behind this subnav item.

It doesn't seem to be a z-index issue.

![flexslider-nav-bug](https://cloud.githubusercontent.com/assets/1815385/9744524/60a4fdd0-563a-11e5-9804-bfbbef9974b9.gif)

**Comment by jeffikus** [comment]
Hi there

That might be an issue with your actual site's CSS, can you provide me with a live url that I can test this on? But yes, most likely a z-index thing. 

Thanks,
