### ISSUE TITLE
slider stops on mobile while scrolling up or down

### ISSUE THREAD

**Issue by Nareshdzx** [woocommerce/FlexSlider#1442]
Slider stops on mobile while scrolling up or down. Please help.

http://kasehdiaventures.com/

**Comment by jeffikus** [comment]
hi there, you are going to need to be a bit more specific than that please. I need to know the mobile that you are testing on, the operating system and browser used. Also, can you please be a bit more descriptive, for example, "I did X and then Y happened, when I was actually expecting Z to happen."
