### ISSUE TITLE
flexslider 'fade' animation not work in IE11

### ISSUE THREAD

**Issue by imalexi** [woocommerce/FlexSlider#1451]
[ origin ]:
slider.slides.css({ "opacity": 0, "display": "block", "webkitTransition": "opacity " + slider.vars.animationSpeed / 1000 + "s ease", "zIndex": 1 }).eq(slider.currentSlide).css({ "opacity": 1, "zIndex": 2 });
[ fixed ]:
slider.slides.css({ "opacity": 0, "display": "block", "webkitTransition": "opacity " + slider.vars.animationSpeed / 1000 + "s ease", transition: "opacity 2s", "zIndex": 1 }).eq(slider.currentSlide).css({ "opacity": 1, "zIndex": 2 });
[ only add ]:
transition:"opacity 2s",
i find it in a janpanese site:http://www9377uo.sakura.ne.jp/sakura/145/

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
