### ISSUE TITLE
Border-radius on flex-control-nav a's square on Chrome only.

### ISSUE THREAD

**Issue by BenRacicot** [woocommerce/FlexSlider#1455]
Hello, I'm having the strangest issue. I have two flexslider's on my home page. On Chrome only, my rule for circle paging control's (see below) actually loads square and border-radius only applies after hovering each one.

``` javascript
// white circles
.flex-control-paging li a{
    display: block;
    background: transparent;
    border: 3px solid white;
    // border-radius: 50%;
    border-radius: 50% 50% 50% 50%;
    -moz-border-radius: 50% 50% 50% 50%;
    -webkit-border-top-left-radius: 50%;
    -webkit-border-top-right-radius: 50%;
    -webkit-border-bottom-left-radius: 50%;
    -webkit-border-bottom-right-radius: 50%;
    width:  15px;
    height: 15px;
    &.flex-active{
        background-color:white;
    }
}
```

On Chrome only ( Version 46.0.2490.86 (64-bit) ) these controls load square. On all other browsers (even Canary) they load according to the CSS. Please see [this link](http://utilidata.wpengine.com) to the development page. 

Any ideas or solutions would be great, thanks in advance.

**Comment by moymadethis** [comment]
I'd just like to add this. I'm also experiencing this issue, which previously worked fine - using the same CSS and javascript as before, with FlexSlider v2.5.0.

I've noticed that when you first load the page this issue occurs but on refreshing (CMD+R) it works fine. Putting the cursor into the address bar and hitting Enter/Return makes the rounded anchors square again - until you interact (hover) with them.

That's about all the information I have right now, will update if I think of anything else.

Would also really appreciate a solution to this :)

**Comment by moymadethis** [comment]
An additional note. I've noticed on 1 page I have 2 carousels in use, only one of them has square direction navigation anchors, the one that is outside the viewport when the page loads. The top carousel which can be seen on loading the page is fine.

If I remove additional content from my HTML templates, so both carousels are in the viewport on load they both display as rounded! 

Hopefully this will go a little bit of the way to helping find a solution for the issue.

**Comment by BenRacicot** [comment]
@moymadethis Hey! Thanks for adding your input. My development website that I've linked to also has 2 sliders on the home page. And also only 1 usually has square buttons. Could you take a look and let me know if our problems do in fact match.

**Comment by moymadethis** [comment]
Hi @BenRacicot! Yes it looks like the same issue, although the unwanted effect occurs on the directional nav on my website. So it looks like it's a problem with both the pagination and prev/next arrows.

It would be interesting to know if you put your "team" slideshow at the top of the website, if the issue was still visible? I have a feeling it's to do with what's in/not in the viewport on load.

When testing the website I haven't been able to detect this issue in anything other than Chrome. Tested on Mac, haven't checked the Windows version of Chrome yet!

**Comment by BenRacicot** [comment]
@moymadethis Wow you're right. It is only the slider that is in the viewport on page load. This is confirmed that its Chrome 46 on Mac and Win 7. All other browsers do not have the bug, I just checked and saw no bug via BrowserStack on Win 7: safari 5.1, ie 9,10,11, Chrome 46,47. And also on my Mac Pro: Safari 9.0.1, Firfox developer, Chrome Canary, AKA 48, and as of just now 49.0.2567.0.

**Comment by moymadethis** [comment]
Another oddity, it seems to only effect the border/other 'outer' elements? Which again, looks like it could be consistent with the problem you're experiencing @BenRacicot.

If I set `border-radius: 100%; ` on the anchor with only a background colour set, the anchor displays perfectly circular. If I add a box-shadow, this displays as a square shadow behind the circle until interacted with when it then corrects itself. Likewise if I set a border, the border is displayed as a square also.

Hope this additional information can also help find a solution.

**Comment by rwrobe** [comment]
Have we found any workaround or hotfix for this until 2.7.0 comes out? Eliminating the box shadow doesn't seem to prevent the issue.

**Comment by guilima** [comment]
This is a problem with the browser not the plugin, however `transform: translateZ(0);` works like a charm

**Comment by moymadethis** [comment]
@guilima @rwrobe personally I always felt it was an issue with the browser as this issue didn't occur before but thought it might be useful to report incase it had a knock on effect and needed to be addressed in the next release or if a temporary fix could be applied. Thanks for the translateZ fix, I'll add that now.

That said, I can't currently see the issue in my browser. I notice my Chrome is version 47.0.2526.73. Maybe this has updated and is fixed. It would be good if someone else can confirm this before closing the ticket?

**Comment by BenRacicot** [comment]
Hey guys, @moymadethis I/we already confirmed that it was specific to Chrome 46... Chrome 47 was released yesterday and the bug is gone. I could not replicate the bug on any other browser via BrowserStack. For historical reasons its good that ticket exists though. Happy coding!
