### ISSUE TITLE
Flexslider 2 flickering between slides on Chrome OS X

### ISSUE THREAD

**Issue by amdrew** [woocommerce/FlexSlider#146]
I'm on OS X 10.7.4 with Chrome 18.0.1025.168. With a basic flexslider setup, and with a "fade" animation, there is flickering between slides. You can briefly see the image behind it. In the latest Safari (Version 5.1.7)  however there is no flickering, and neither in FF 12. Strange, since chrome and safari are both webkit.

Also I should note that in Chrome Canary (20.0.1133.0) There is no flickering so could quite possibly be a bug within the current Chrome for Mac. I haven't tested on Windows.

**Comment by tylik1** [comment]
Still happening for me,  after position:relative. Release 2.6.1

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
