### ISSUE TITLE
Control Nav Points not working after Hight Adjustment

### ISSUE THREAD

**Issue by ruebenacker** [woocommerce/FlexSlider#1472]
The Control Nav Points under the images are not working after smothHeight adjustet the height from high to low.  Can't click them. Verified on Firefox 43.0.1 and Safari 9.0.2 (both latest versions available). 
Contact me if you need an example to reproduce the issue.

**Comment by jeffikus** [comment]
Hi there

Please can you provide a url for me to see the behavior and test on?
