### ISSUE TITLE
FlexSlider covers up my webpage background image

### ISSUE THREAD

**Issue by donahrens** [woocommerce/FlexSlider#1479]
I've installed the FlexSlider and everything is working fine. However, the slider is covering up the background image on my webpage.

**Comment by donahrens** [comment]
I should have been more specific. When I added the FlexSlide to my webpage the entire webpage is covered with a white background occluding the background image I have for the website.

**Comment by jeffikus** [comment]
Hi there, do you have a url for me to test on?

**Comment by donahrens** [comment]
Thanks for the response. The url is http://encinal.org/index2.php.

Thanks,
Don Ahrens

**Comment by donahrens** [comment]
Have you had a chance to look a the URL I sent?

Thanks,
Don
