### ISSUE TITLE
If one image, hide direction and control nav

### ISSUE THREAD

**Issue by soire** [woocommerce/FlexSlider#148]
Hi!

First, I love FlexSlider! 

I have my CMS feeding FlexSider and there are some galleries that only contain a single image. I am wondering how I might enhance the current functionality to hide the Direction and Control navigations when there is only one image in the slider? My design would certainly look at lot better if there was no controls or navigation for a single image. 

Any insight?

Thank you!!

**Comment by huykon** [comment]
@tylerxo I have tried your code it still shows nav when only have 1 item. How can I fix it?
