### ISSUE TITLE
Wrong css rules for .flexslider

### ISSUE THREAD

**Issue by burtek** [woocommerce/FlexSlider#1491]
In the flexslider.css file line 84-87 contain rules for .flexslider's box-shadow property. They have an empty string '' at the beginning, which produces error and incorrect displaying of slider:

``` css
  -webkit-box-shadow: '' 0 1px 4px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: '' 0 1px 4px rgba(0, 0, 0, 0.2);
  -o-box-shadow: '' 0 1px 4px rgba(0, 0, 0, 0.2);
  box-shadow: '' 0 1px 4px rgba(0, 0, 0, 0.2);
```

Theese empty strings should be removed.

**Comment by potasiyam** [comment]
Just found out this issue. Why do we need box shadow in first place? Default style should have minimal and simplest look.
