### ISSUE TITLE
Will not respond

### ISSUE THREAD

**Issue by justkristin** [woocommerce/FlexSlider#1499]
Sorry to bother you all, but we are trying to basically duplicate a flexslider install we have on another (two) site(s), but we cannot get the flexslider to respond on this third one!

The ones that work:
http://endextinction.org/species/gorilla (Drupal)
http://www.sandiegozoo.org/roaringforward/ (flat)

The one that doesn't work:
http://www.sandiegozoo.org/centerforplantconservation/ (flat)

We have tried moving the script embeds and initializations around in the index file, but to no avail.
What would make this thing stop being responsive?

**Comment by jeffikus** [comment]
Hi there

I can see a js error on the site, 

Not allowed to load local resource: file:///Macintosh%20HD/Users/Dennis/Documents/Sites/ZooDrupal/sites/all/themes/zoostrap/css/webfonts/268E41_1_0.woff

Looks like your site is missing a font file.

Thanks,

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
