### ISSUE TITLE
Touch Drag Functionality for Desktop - Flexslider

### ISSUE THREAD

**Issue by surjithctly** [woocommerce/FlexSlider#1503]
I can see an issue opened on 2012 and closed without making it.

So, is there any hope for this? Its been years and technologies changed.

Would love to see that effect.

~Surjith

**Comment by TiagoDeSousa** [comment]
I'd love to see that effect either +1

**Comment by haxkep** [comment]
+1

**Comment by kubik101** [comment]
+1

**Comment by odendoak** [comment]
+1
