### ISSUE TITLE
Flex slider does not stop on last slide

### ISSUE THREAD

**Issue by rrhussain** [woocommerce/FlexSlider#1504]
Hi,
I would like to stop flex slider on last slide because it jumps back to the first slide. I am using mouse wheel option true to give user control to move slides through mouse wheel.

I want to stop slide with mouse wheel interaction when it is on last slide. mean don't go to back on first slide just work from last slide in reverse order don't go forward.

I will appreciate your help i tried all methods but no luck.

**Comment by eglyte** [comment]
try [this](http://stackoverflow.com/questions/16072307/flexslider-stop-at-first-slide-after-loop)

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
