### ISSUE TITLE
smoothHeight with reverse causes incorrect height calcuations

### ISSUE THREAD

**Issue by pdkn** [woocommerce/FlexSlider#1505]
looks like setting reverse= true cause the smoothHeight function to miss calculate target height.
`$('#myflexslider').flexslider({
            animation: "slide",
            slideshowSpeed: 5000,
            directionNav: false,
            controlNav: true,
            smoothHeight: true,
            reverse: true
        });`

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
