### ISSUE TITLE
Set Interval for each image

### ISSUE THREAD

**Issue by joshiamit24** [woocommerce/FlexSlider#1508]
Can we set interval for each image in slider. I know we can set interval for whole slider for all images. But I need to show some images as per time set by user.

**Comment by jeffikus** [comment]
Can possibly look into this for the 2.7.0 release.

**Comment by joshiamit24** [comment]
When this will be released?
ThanksAmit Joshi

Date: Fri, 18 Mar 2016 06:03:54 -0700
