### ISSUE TITLE
Slides twice on touch when swipe starts on directional arrow.

### ISSUE THREAD

**Issue by mikaelmattsson** [woocommerce/FlexSlider#1521]
This can be seen in the example here: http://flexslider.woothemes.com/index.html

If you start swiping from a directional arrow the slide will slide twice. This doesn't happen when the slide loops.

**Comment by mikaelmattsson** [comment]
For anyone else looking for a temporary fix, put this in the start function:
```
$('.my-slideshow').flexslider({
    start: function (el) {
        el.find('.flex-direction-nav').on('touchstart', function (e) {
            e.stopPropagation();
        });
    }
});
```

**Comment by jeffikus** [comment]
Thanks, I'll have to take a look as part of the 2.7.0 release cycle, busy with 2.6.1 at the moment.
