### ISSUE TITLE
undefined jquery in jquery.flexslider.js line 1195

### ISSUE THREAD

**Issue by bibliofille** [woocommerce/FlexSlider#1524]
I'm trying to integrate Flexslider (v2.6.0) into a WordPress site using Bones as the starter theme. 

I downloaded the plugin and hooked up the files, but I'm getting an uncaught error: undefined jquery on line 1195 of jquery.flexslider.js. 

Anyone have an idea of what could be causing this? I'm currently developing locally so I don't have a URL to share. I'm using Chrome Version 50.0.2661.75 (64-bit).

**Comment by jeffikus** [comment]
Please give context of how you are including Flexslider in your code? Also, this might be more of a question for the Bones developers.

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
