### ISSUE TITLE
randomized, yet first slide always appears briefly

### ISSUE THREAD

**Issue by webguy262** [woocommerce/FlexSlider#1525]
Since adding flexslider, I've been running it using 'animation: fade' and 'fadeFirstSlide: false.' I get a quick load of first slide, and no flash a few seconds later when the nav loads. The first slide basically gets "pre-loaded' and when the rest are ready, the nav appears, without the first slide appearing to move. Works fine.

But now I would like to randomize the load order of the slides. Problem is, the first slide (code-wise) still "pre-loads" for a bit, then gets abruptly replaced (no fade) by the random one when the control nav loads.

Is there anyway to predetermine the random load order, and "pre-load" the randomized first slide?

**Comment by webguy262** [comment]
Hoping to get some feedback on this issue. Is there another forum where I should post?

**Comment by jeffikus** [comment]
Hi there, do you have a URL where I can see this happening?

**Comment by webguy262** [comment]
You can look here...

http://www.fisherwallace.com/pages/slider

... reload a few times and you'll see first slide in code always appears.

When the nav dots load, the first random slide also appears.

If the random slide happens to be first slide in code, great!

But otherwise, first coded slide get abruptly replaces by first random slide.

Would LOVE to be able to have random slide determined first, then have it designated 'fadeFirstSlide: false' and then have nav dots and other random slides load.

Possible?

**Comment by webguy262** [comment]
@jeffikus Did you get a chance to take a look? Would love to get your thoughts!

**Comment by webguy262** [comment]
@jeffikus Is taking a look at this on your to do list?

**Comment by jeffikus** [comment]
@webguy262 it is, just not this week. Will look next week.

**Comment by jeffikus** [comment]
Have scheduled for Monday, didnt get to this this week unfortunately :(

**Comment by webguy262** [comment]
Great!

**Comment by jeffikus** [comment]
hi there

I had a look at this, this is a shopify theme right? or is this custom?

**Comment by webguy262** [comment]
Custom

**Comment by jeffikus** [comment]
This might be a weird thing to test, but just wrap the _true_ and _false_ parameters inside quotations, like "true" and see if that changes anything.

**Comment by webguy262** [comment]
Sorry for the delay... overlooked your response.
Adding quotes did not make any difference.
Need a way to randomize order, THEN show 'first' random slide, then load nav, etc.
Possible?

**Comment by jeffikus** [comment]
@webguy262 so what you'd need to do is to random the images before you output the markup - so for example, if you are pulling the images using WordPress, you would randomize that query. Does that make sense?
