### ISSUE TITLE
Chrome, Safari, IE initial display issue

### ISSUE THREAD

**Issue by whyisjacob** [woocommerce/FlexSlider#1529]
in Chrome, Safari, and Internet Explorer there seems to be an issue when the first instance of the first slide loads up it displays as if it's halfway between the first and second slides.

All 3 browsers are up to date

![slider-issue](https://cloud.githubusercontent.com/assets/18726040/14993408/df2aea04-1127-11e6-9f4b-a24811fac13e.jpg)

**Comment by jeffikus** [comment]
Please post the url so I can take a look.

**Comment by whyisjacob** [comment]
This particular issue is on a closed site (user / pw needed) I've been trying to replicate it on sites like codepen and jsfiddle but was un-successful in that endeavor

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
