### ISSUE TITLE
Flex slider goes blank after last slide on touch devices---NEED HELP !!!

### ISSUE THREAD

**Issue by ha00120655** [woocommerce/FlexSlider#1532]
I have 2 slides and if I use slide horizontal ,it works fine. However when I use the fade effect, on touch devices , initially it works fine for the two slides but after the second slide is displayed, it does not moves back to the first one, rather displays a blank slide. It actually does not create a blank slide but changes the opacity of both the li's to 0.

Can someone help ?

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
