### ISSUE TITLE
LOOP with thumbnails not sync correctly

### ISSUE THREAD

**Issue by seltix5** [woocommerce/FlexSlider#1536]
hi,

after the last slide, wen it loops back to the first the thumbnails dont sync.
them thumbnails slide only sync after you click "NEXT" two more times...

example : http://flexslider.woothemes.com/thumbnail-slider.html

NOTE : i know the example doesnt has LOOP activated but it still there. as i posted on this issue (https://github.com/woothemes/FlexSlider/issues/1535) you can still click in the next button even if it is not visible.

thank you.

**Comment by jameschetwood** [comment]
+1

**Comment by seltix5** [comment]
Hi, 
Yes apparently it still is the same problem, but with just one slider. 
After all this time the problem wasn't still corrected?
:-\
