### ISSUE TITLE
Slides inline-block instead of floated left?

### ISSUE THREAD

**Issue by IvanovWeb** [woocommerce/FlexSlider#1541]
Flexslider is forcing the slides to be floated left by adding a style property. 
That makes positioning the slides not very flexible. IN particular, having every second slide on a second row and with different width. 
Can adding that style property and particularly be avoided? 

Thanks

**Comment by hvsh** [comment]
@IvanovWeb you can add **!important** to the display:inline-block rule in your css.

**Comment by IvanovWeb** [comment]
That was the first thing I tried. It didn't work. I tested in Firefox. 
I ended up modifying the core code. 
I definitely see this as a functionality where flexslider gas one more var to check if it should force the float and display style for the slides. 
Thanks for your help. 
On Jun 2, 2016 9:00 AM, Hasan <notifications@github.com> wrote:@IvanovWeb you can add !important to the display:inline-block rule in your css.
