### ISSUE TITLE
flex-control-nav ->a not hover event?

### ISSUE THREAD

**Issue by charrysong** [woocommerce/FlexSlider#1542]
I found a of control-nav just has click event,when  I user the plug.is that  a bug?
![dd](https://cloud.githubusercontent.com/assets/16949356/15595725/1de8c868-23f4-11e6-9c7d-7d8e29650b54.png)
@carcer

**Comment by jeffikus** [comment]
Can you elaborate a bit more? Or share a live url so I can see what you mean.
