### ISSUE TITLE
Images not resizing upon changing window orientation

### ISSUE THREAD

**Issue by pyxis828** [woocommerce/FlexSlider#1544]
If user initially starts in portrait view, then changes to landscape view, instead of showing 1 image and resizing it, 2 images are shown (in this particular slider there are only 2 images).  When swiping to the second screen, it is blank.  If the user then switches back to portrait view, the first image gets cut in half, with the first half visible as the first image, and the second half visible as the second image.  The only way to get the images to resize is to scroll down the screen so that the slider is no longer visible, then to scroll back up, at which time, the images will properly resize.

I can get it to play a little nicer by changing this:
// FADE&&SMOOTHHEIGHT || SLIDE:
 if (!fade || (fade && slider.vars.smoothHeight)) { $(window).bind("resize orientationchange focus", methods.resize; }  <-- you are missing the () after resize here

to this  (no conditional):
 $(window).bind("resize orientationchange focus", methods.resize());

Like this, there are still 2 images in the first position in landscape view, but the second image shows in the right place when swiping, although it doesn't resize at all.  And portrait view doesn't get broken when switching back to it.

I can't give you a link

**Comment by vlrprbttst** [comment]
+1

**Comment by MichaelMackus** [comment]
I think https://github.com/woocommerce/FlexSlider/commit/fb468682543a607fa3a0fd89a11e68f7134d0575 broke this, actually. Now, the event is bound to the return value of `methods.resize()` (which is likely nothing).
