### ISSUE TITLE
Make slider image draggable

### ISSUE THREAD

**Issue by lunglung876** [woocommerce/FlexSlider#1548]
What is the reason of setting draggable to false on slider image?
I set draggable to true and it seems to be working fine.

Thanks.

**Comment by jeffikus** [comment]
Hi there

Can you please supply example code and/or a URL that this is happening on? Thanks,

**Comment by lunglung876** [comment]
https://github.com/woothemes/FlexSlider/blob/master/jquery.flexslider.js#L150

I am trying to make images in slider draggable. Just wondering if setting draggable to true would create some bugs that I am not aware of.
