### ISSUE TITLE
2nd slide loading briefly below 1st slide

### ISSUE THREAD

**Issue by mtimes** [woocommerce/FlexSlider#1551]
I have flexslider set up on a site we're building and everything works perfectly except when the slide show is loading.

If you take a look at the site here: http://mtimesmedia.com/test8/ you'll see the issue.

The first slide loads and then the second slide appears below it for a second and then the slideshow appears correctly.

What am I doing wrong?

Thanks in advance for any help you can be.

**Comment by mordesani** [comment]
Same issue here.
