### ISSUE TITLE
wordpress theme n flexslider

### ISSUE THREAD

**Issue by bitniko** [woocommerce/FlexSlider#1553]
hi, im using [bones wordpress starter theme](http://themble.com/bones/) and im trying to get started with flexslider using the examples described here [https://woocommerce.com/flexslider/](https://woocommerce.com/flexslider/) and here [http://flexslider.woothemes.com/index.html](http://flexslider.woothemes.com/index.html) and none of the code seems to work, am i missing something?
what are the propers steps to make flexslider working on the initial index page with slides using wordpress with bones starter theme??
i can use [flexslider plugin](http://www.fergusweb.net/software/flex-slider/) for wordpress but its better if do a manual code insertion??

**Comment by Hlsgs** [comment]
This is not the proper place to ask these question as they are not actually Bones related. Implementing a slider or a hamburger menu is the same in any WP theme and has nothing to do with Bones itself. try the specific forums for the projects you want to implement or stackoverflow.

**Comment by jeffikus** [comment]
I would suggest using one of the existing WordPress plugins for this, such as [WooSlider](https://woocommerce.com/products/wooslider/).
