### ISSUE TITLE
Arrows: Use < and > character in flexlider-icon instead of f001 and f002 and define alternative font

### ISSUE THREAD

**Issue by crazy4chrissi** [woocommerce/FlexSlider#1559]
We had some cases in which the web font flexlider-icons was not loaded correctly.
Symbols "f001" and "f002" were displayed instead.

This can happen for example when your internet connection is fragile (e.g. mobile internet). There are also people that disable web-fonts:
https://www.techpowerup.com/forums/threads/disabling-web-fonts-in-mozilla-firefox-and-google-chrome.184198/

To make the flexslider navigation more robust, I would propose to use the standard characters < and > instead of \f001 and \f002 and adjust the flexslider-icons font accordingly. Then you could also give a alternative font that will be used if loading the font does not work.

I already edited the font in fontforge and tried it. It works well for me. In case you want to, I can prepare a pull request.

**Comment by jeffikus** [comment]
A pull request would be greatly appreciated! Feel free to tag me in the pull request comments! Also, can you do the pull request onto the 2.7.0 branch? https://github.com/woothemes/FlexSlider/tree/release-2-7-0 

Thanks for helping!
