### ISSUE TITLE
Flexslider Doesn't Work in SHTML

### ISSUE THREAD

**Issue by colleenlockard** [woocommerce/FlexSlider#1564]
I have a FlexSlider in the footer of my web site, which is an include file (shtml).  The slider won't work properly when part of an include, but it does work properly in html.  I have checked on the file paths to make sure the jQuery/js files are called properly, but the slider still doesn't work.  

What modification do I need to make for FlexSlider to function properly in shtml?  

http://www.bishopsgatecomm.com/PerfectDetail/index.shtml 
(FlexSlider is located at the bottom of the page under "Testimonials")

I thank you in advance for your help.

**Comment by colleenlockard** [comment]
Wondering if the issue above was overlooked.  Is more information needed?  Thanks.

**Comment by jeffikus** [comment]
Hi there

Have you tested with version 2.6.2?
