### ISSUE TITLE
Improve Flexslider Accessibility

### ISSUE THREAD

**Issue by zipymonkey** [woocommerce/FlexSlider#1580]
I've noticed that the 2.6.2 release of FlexSlider is not easily accessible via the keyboard.  

Here are are some suggestions I have based on the [WAI Carousel Concepts Tutorial](https://www.w3.org/WAI/tutorials/carousels/): 
- Remove keyup from eventType 
- Add arai-live="polite" attribute to flex-caption.
- Add role="button" attribute to controls
- Use a input of type image for thumbnails so they can be accessed via the keyboard.  (Alternatively wrap the image in a link).

**Comment by jeffikus** [comment]
Is this a problem only since 2.6.2 or was this present in 2.6.1 as well?
