### ISSUE TITLE
Items in slider get out of synch after a few slides.

### ISSUE THREAD

**Issue by LaneLourcey** [woocommerce/FlexSlider#1586]
The flex slider works on my desktop and on my note 5, but my boss's smaller cellphone and a few resolutions I test at in chrome have this issue. The items get concatenated by the edges of the screen.
I'm not sure if the issue is the slider isn't seeing my width correctly, or if the issue is with the margin.
Here is my code:

$('#product-slider').flexslider({
    slideshowSpeed: $('.slide-show').attr('data-swap-frequency') \* 1000,
    animation: "slide",
    animationLoop: false,
    itemWidth: 160,
    itemMargin: 15,
    maxItems: 5,
    minItems: 2,
    direction: "horizontal",
    startAt: 0,
    slideshow: false,
    controlsContainer: $(".custom-controls-container"),
    customDirectionNav: $(".custom-navigation a"),  
    move: 0
  });

www.asseenontvhot10.com

**Comment by diogogomeswww** [comment]
I think it's a CSS problem.

**Comment by LaneLourcey** [comment]
Any ideas on how the css is causing a problem? the images are the same size that I pass into the slider, and so are the margins. 
I'm not sure what else could be at play.

**Comment by diogogomeswww** [comment]
I think that removing these lines on the css file 
https://cdn5.bigcommerce.com/s-618e0qhzbg/templates/__custom/Styles/theme.css?t=1473693841:
`.responsive .page .product-grid li:nth-child(4n+4) {
    margin-right: 0;
}`

Hope that it helps.

**Comment by LaneLourcey** [comment]
That didn't seem to fix the problem. I checked all of the elements and they're all the same size with the same margin. I can't find any css property that I think affects it, it seems to be something I'm doing wrong with the slider itself.

**Comment by LaneLourcey** [comment]
I've found that the slider moves the wrong amount of pixels. On the 360px breakpoint, when you click the button to move it to the right it moves 337px when it should move 350 to slide two images.

**Comment by diogogomeswww** [comment]
Hi,

Did you fix this?
I don't see any problem now...

**Comment by LaneLourcey** [comment]
No i havent fixed it. There are a few resolutions you hardly notice though.
