### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by tebert250** [woocommerce/FlexSlider#1588]
Occasionally, the slider will speed up the rotation of slides. It will start going really fast and then it will slow back down.

I don't have a public example for you to access. And it isn't consistent so it is hard to debug.

I really am wondering if you have heard of this problem and already have a solution.

**Comment by jeffikus** [comment]
Hi @tebert250 - i haven't heard of that, what version are you using?

**Comment by tebert250** [comment]
Unfortunately, the person who put the javascript file on the site didn't leave the information up at the top to know what version it is. I've attached the file here so that maybe you can determine the version.
[jquery.flexslider-min.txt](https://github.com/woothemes/FlexSlider/files/487516/jquery.flexslider-min.txt)

**Comment by jeffikus** [comment]
Ok, so what I suggest is replacing their code with this (make a backup first though!!) https://github.com/woocommerce/FlexSlider/blob/master/jquery.flexslider-min.js and let me know if the problem is resolved.
