### ISSUE TITLE
Thumbnail Callback

### ISSUE THREAD

**Issue by lewismalpas** [woocommerce/FlexSlider#1589]
Hi,

Is there a callback after clicking a thumbnail?

I have restyled the thumbnails so they appear in an overlay above the website/carousel, I want to close the overlay once a thumbnail has been clicked and the slider has navigated to the slide containing the clicked image.

Thanks,
Lewis.

**Comment by jeffikus** [comment]
There are a few callbacks, not sure if they will help, but they fire when slides transition. They are:
**start
before
after
end
added
removed**
You can read about them here -> https://github.com/woocommerce/FlexSlider/wiki/FlexSlider-Properties
