### ISSUE TITLE
How to run slide on image hover ?

### ISSUE THREAD

**Issue by samarthpathak3** [woocommerce/FlexSlider#1593]
Hello,
Greetings

I want to run the slides on hover of image. The slider should start sliding whenever the cursor is on image. How should do this? Please help me.

Thanks,
Samarth

**Comment by jeffikus** [comment]
That sounds like you should write your own jQuery event listener for this. Something like https://api.jquery.com/mouseover/ and then load the slider. Let me know if that makes sense to you.
