### ISSUE TITLE
Flexslider fails to initialize properly on hidden target.

### ISSUE THREAD

**Issue by fatfantasma** [woocommerce/FlexSlider#1594]
It seems all of the carousel plugins seem to have the same issue because of jquery can't get the 'width' of a element if it's not visible on the page.  Thus the plugins fail to initialize properly.

I have read similar issues here as well has a the relevant stackoverflow questions.  Bootstrap tabs, Jquery Mobile pages, hidden divs, modals, etc all have the same issue.  Nobody has a perfect solution.

I am currently working on a jquery mobile app. All of the pages are of course hidden.  When I show a page I CAN initialize the flexslider.  Of course the page is already shown and initializing flexslider has the undesirable effect of 'popping' in the slides and moving down the below html to make room.  This is purely an aesthetic issue.  It would be awesome if the flexslider was already initialized before the page show for nice page transitions and such.

The last three days I have been researching this issue and trying to fix or at least a work around.  I did find some success modded (hacking : ) )the flexslider.js code in a blind attempt to fix the issue.   Every time I got close to a workaround another problem popped up.  It just became a mess to work with.

My general hack was to have an extra image (a copy of slide 1) and try to init flexslider under it the remove the extra image to show the true flexslider.  I used the current $(window).width() to set the target elements width that where hiding off screen.  Init flexslider, Then using the start callback reset the original elements so they are visible on screen.  There is way more to this which is why I abandoned the idea. :(  It got close tho. :)

Anyway, can this plugin be fixed so it will work with hidden targets?  If so, it would make web apps so much nicer.

Thanks for a great plugin!

**Comment by jeffikus** [comment]
Hi there, we dont offer official support for jQuery mobile as that is a very old and project - I would suggest moving over to a project like the Ionic framework for building mobile apps. But, having said that have you tried this? http://stackoverflow.com/questions/9314147/flexslider-loads-once-with-jquery-mobile
