### ISSUE TITLE
Flexslider swipes being muddled with iOS10 touch swipe

### ISSUE THREAD

**Issue by themightyant** [woocommerce/FlexSlider#1598]
Hi,
in iOS 10 swiping left right also scrolls page up and down more easily than before meaning that sliders can scroll off the screen while the slide is animating left/right.

Is there a way to disable touchmove while the slide is animating and restore it when finished?  
I tried the before and afrer properties on flexslider init but coulnd't get it to work

thanks

**Comment by martinkamara** [comment]
Yes it is totally all over the place when swiping. In my case I added this as a quick work around, but yeah it would be nice if it would be fixed in flexslider.

`$('.flexslider').on('touchmove', function (e) { e.stopPropagation(); });`
