### ISSUE TITLE
flexslider horizontal slider support 

### ISSUE THREAD

**Issue by kevalbhatt** [woocommerce/FlexSlider#1601]
Is it possible to have content scroll horizontally with slider ?

Example:

![untitled](https://cloud.githubusercontent.com/assets/8266504/19212470/654dd664-8d6f-11e6-841d-e64989737bcd.png)

In screenshot you can see last image is in scroll so now if flexslider  come to image which is visible active in screenshot and after that it goes to next one then at that time if flexslider  slide other content to left then it will help full.

something like (http://bootsnipp.com/snippets/featured/thumbnail-carousel-single-image-sliding)

**Comment by jeffikus** [comment]
That should be possible by using the standard carousel example [here](http://flexslider.woothemes.com/basic-carousel.html) and adding the 'move' param as documented [here](https://github.com/woocommerce/FlexSlider/wiki/FlexSlider-Properties).

Reopen if you get stuck.
