### ISSUE TITLE
Changing flexslider direction on the fly

### ISSUE THREAD

**Issue by stratboy** [woocommerce/FlexSlider#1602]
HI, I need to change direction base on breakpoints. I tried to save a flexslider instance and then use flexsliderinstance.vars.direction but it doesn't work. Probably I should destroy and reinitialize flexslider, but it seems not to have any reliable method for doing it.

So how can I change the direction on the fly OR reinitialize flexslider?

Thank you, regards

**Comment by vhinmanansala** [comment]
Not sure if you already solved this but you can try this [**Best way to disable FlexSlider in small viewports? #774**  ](https://github.com/woocommerce/FlexSlider/issues/774). Found it on https://github.com/woocommerce/FlexSlider/issues/636

**Comment by stratboy** [comment]
I ended up with a throttled function that erases the related dom onresize, creates a clone from a backup template, re-inject it into the document and reinstantiate flexslider with changed options. Messy, but works. Still, it's a shame that the main options aren't swappable on the fly AND that flexslider doesn't have at least proper functions to cancel itself.

Alvin Manansala ha scritto:
