### ISSUE TITLE
No fully responsive with slide/horizontal mode

### ISSUE THREAD

**Issue by stratboy** [woocommerce/FlexSlider#1605]
Hi, I've found out this and I think it's a bug. If animation is slide and direction is horizontal, then the slides widths are dyinamically setted by flexslider (inline styles). Ok. 
But that doesn't work in every case. If I decrease the window size, then at a certain point it will stop recalculating/assigning the slides width, making it not fully responsive. If I then increase the windows size, it will restart to correctly recalculate sizes.

I've got this issue with both picture elements (ul > li > picture > img) or simple img (ul > li > img) 

Regards

**Comment by Bhaskar-Malladi** [comment]
I am also facing same issue

**Comment by jeffikus** [comment]
Please provide a url that showcases this so I can replicate the issue.
