### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by ekkis** [woocommerce/FlexSlider#1606]
I have an issue where the two arrows that show up on the left/right are partly cut off.  also, clicking on the left does not go to the previous slide but to the next.  I have the version available from bower (at present, 2.6.3).

I can fix these things but don't want to waste my time if the pull request is never going to be accepted.  I see there are 42 pull requests awaiting.  doesn't inspire much confidence.  should I bother?

**Comment by ekkis** [comment]
incidentally, the issue of the arrows being partly cut off owes to a height/width that is set to 40px in `theme.less` (`.flex-direction-nav { a {} }`) which is not sufficient to display the character.  these settings should be removed altogether but users can override them in their code as a temporary fix

**Comment by ekkis** [comment]
as for the left arrow moving forward instead of backward, I can't seem to figure out why.  Line 320 in the `.js` seems to do the correct thing:

`          slider.directionNav.bind(eventType, function(event) {
                event.preventDefault();
                var target;
`
but when I click on the left arrow I see that `$(this)` contains class `flex-next` regardless of which arrow I click on.  very strange.

**Comment by ekkis** [comment]
I'd also like to enhance the module to not display the words "next" and "previous" as the carets are sufficient to indicate direction

**Comment by ekkis** [comment]
ok.  I figured out why the left arrow goes right.  in trying to fix the cut-off carets I set the width to 100% which means that the two divs overlay each other.  setting width to 4em. fixed this problem

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
