### ISSUE TITLE
Demo is missing script on front end

### ISSUE THREAD

**Issue by rtpHarry** [woocommerce/FlexSlider#1607]
The demo has a JS preview pane but it doesnt match the actual code thats required to get the snippet working.

See this section:

https://github.com/woocommerce/FlexSlider/blob/master/demo/dynamic-carousel-min-max.html#L197

Is not included in the front end preview further up the document.

**Comment by jeffikus** [comment]
Thanks, will update the code, but just to clarify, the demo JS is the barebones, there are some little extra things on top to add some gloss. I'll update it to make that clearer :)

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week and updated a large portion of the demos, please let me know if the issue persists after updating.
