### ISSUE TITLE
On window resize flexslider is not working as expected

### ISSUE THREAD

**Issue by Bhaskar-Malladi** [woocommerce/FlexSlider#1609]
![image](https://cloud.githubusercontent.com/assets/8006156/19467698/2cc628e6-9530-11e6-9e8e-41472166a6ba.png)

When resizing the window in tablet view I moved all the slides to right and after I am trying to resize the window the slder will look like this I tried the slider.flexAnimate(0) it doesn't work for me.. 
Any help thanks...

**Comment by jeffikus** [comment]
Please provide a url so I can test this.

**Comment by inier** [comment]
try this url： http://codepen.io/moza/pen/bgqoVe  
change window fullscreen or small

**Comment by inier** [comment]
yeah, I have this problem too. 
but, this bug  without firefox.

**Comment by Dulanji** [comment]
I have the same problem. Is there any solution

**Comment by jeffikus** [comment]
@Dulanji what version are you testing with?

**Comment by Dulanji** [comment]
http://flexslider.woothemes.com/dynamic-carousel-min-max.html
Im using this version
