### ISSUE TITLE
Not an issue, needing help using within WordPress

### ISSUE THREAD

**Issue by nwtech** [woocommerce/FlexSlider#1611]
Currently using this in WordPress to show the top 5 posts from a certain category.

I'd like to change the Slider's  control navigation. Without styling, it's currently setup in an <ol> and displaying sequential numbering. I'd like to replace the numbering with the posts' title and category, so I can style it similar to this: https://imgur.com/a/oNjXt

Is there a way to pull in that post info using jquery and maybe data fields from the loop of posts?

I think, on line 222, I might be able to replace `j` with something like `("h2.slider-post-title").attr("data-original-title")`

Any ideas?

**Comment by jeffikus** [comment]
You would follow the example here http://flexslider.woothemes.com/thumbnail-slider.html where the 2 are sync'd - however in your case, you would have the post titles instead of the second sliders images. Make sense?

**Comment by jeffikus** [comment]
Reopen if you get stuck.
