### ISSUE TITLE
FlexSlider adding a unwanted picture

### ISSUE THREAD

**Issue by Prototips** [woocommerce/FlexSlider#1612]
Hello!
Principally there is problem with that I add 2 pictures to FlexSlider and it shows, that there is 3 pictures, the last picture is just blank, white...
This is 2nd picture -
http://image.prntscr.com/image/becb23af68434995a6f6347dbe11c8ce.png
And after this picture should be the first (cuz I added 2 pictures), but no, there is blank - 
http://image.prntscr.com/image/30bf926a986143a6b83b339a99ca0b2f.png
And here you can see, I have added only 2 pictures. Any ideas, why it`s showing the third, blank picture?
http://image.prntscr.com/image/c1b3bd1b47da4764a6461d10b86b489e.png

EDIT: Okay, this is interesting. I was out, after few hours came back and now in Theme Optins -> Home Slider there was 3 slides. Deleted last one and there is no more blank picture.

**Comment by jeffikus** [comment]
Ok, glad you seem to have found the issue. Reopen if the issue persists.
