### ISSUE TITLE
Problem on mobile devices

### ISSUE THREAD

**Issue by kenerly** [woocommerce/FlexSlider#1617]
FlexSlider is not working correctly on mobile devices for me. 

Code
`<section class="feedback images-bg animate parallax2">
            <div class="container"><br>
                <div class="feedback-title">What customers say</div>
                <em>“</em>
                
                <div class="flexslider">
                    <ul class="slides">
                        <li>
                            <p>As described and plan to order more...2 weeks and doors squeak free!!</p>
                            <strong>Ebay Feedback on Door Hinge</strong>
                        </li>
                        <li>
                            <p>Just like the one I had on my wall as a kid. I can't believe it.</p>
                            <strong>Ebay Feedback on 96 Rock Tag</strong>
                        </li>
                        <li>
                            <p>Wow just like high school wish I had my 1980 Z-28 back. Thanks great service!!!</p>
                            <strong>Ebay Feedback on 96 Rock Tag</strong>
                        </li>
                    </ul>
                </div>
            </div>
            <img src="images/other-images/feedback.jpg" alt="">
        </section>`

Site is located [HERE](http://everythirdday.net)
Its the customer feedback section, near the end of page.

**Comment by jeffikus** [comment]
Hi there, I'm really not sure what the problem is for you here,

(1) what is the behavior that you are expecting to see
(2) what are you currently experiencing?
