### ISSUE TITLE
Flexslider appearing under images in Shopify?

### ISSUE THREAD

**Issue by RussOlorun** [woocommerce/FlexSlider#1618]
I'm having an issue with Flexslider in Shopify in that it is appearing under the images on the homepage. It will resolve itself if I very slightly resize the browser window. Any ideas?

![flex-01](https://cloud.githubusercontent.com/assets/24522905/21098068/622e9c84-c05f-11e6-95fe-912ef9912ead.jpg)

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, if this is a Shopify theme, they will need to update their theme in order to resolve the issue.

**Comment by RussOlorun** [comment]
Hey Jefficus, thanks for the update. As it happens I've changed the Shopify theme a while ago so this is no longer an issue for me. Thanks all the same.

**Comment by jeffikus** [comment]
ok, i'm glad the issue was resolved for you, enjoy the new theme :)
