### ISSUE TITLE
FlexSlider won't initialize in while website is under construction.

### ISSUE THREAD

**Issue by ghost** [woocommerce/FlexSlider#1623]
I followed all the instructions to the letter while implementing the Jquery plugin "FlexSlider", but it won't initialize. I verified that Jquery is working by removing the plugin and writing a simple script that just puts a red border around all my <divs> and that worked. I verified the pictures were "path-ed" correctly by removing the links to the scripts (both to Jquery and FlexSlider), and the pictures showed up. So I'm not sure what the issue would be. I am using the latest versions of both Jquery and FlexSlider.

**Comment by keefyhub** [comment]
Do you have a link to the site or could you post the code somewhere (like [Codepen](http://codepen.io/) or [JSFiddle](https://jsfiddle.net/))

**Comment by adammcgurk** [comment]
I apologize for the lateness of my reply, it has been crazy, but I'm back to normal now. 
Here it is on JSBin:
https://jsbin.com/zetazirizo/edit?html,css,js,output

**Comment by keefyhub** [comment]
no worries, it looks like (from the example you have given) that the path to `jquery.js`, `jquery.flexslider.js` & `flexslider.css` might not be correct. Have you tried using a CDN for it? [link](https://cdnjs.com/libraries/flexslider)

I know you said you checked the paths, but all I did in the jsbin example was change the path to the 3 resources and it worked fine.

If that doesn't solve it, do you have any javascript errors in the console?
