### ISSUE TITLE
flex slider won't start at first slide,after refresh a browser it start from last slide

### ISSUE THREAD

**Issue by vinaymcscet** [woocommerce/FlexSlider#1628]
$('.project-slide-section').flexslider({
    animation: "fade",
    controlNav: false,
    animationLoop: true,
    slideshow: true,
    itemWidth: 210,
    slideshowSpeed: 4000,
    maxItems: 1,
    asNavFor: '.right-projectdtl-section'
    });

  $('.right-projectdtl-section').flexslider({
    animation: "slide",
    controlNav: false,
    directionNav:true,
    slideshow: true,
    startAt: 1,
    slideshowSpeed: 4000,
    animationLoop: true,
    sync: ".project-slide-section",
    start : function(slider){
       $('.slideno #slidecount').text(slider.count);
       },
    after : function(slider){
      $('.slideno #slidecount').text(slider.currentSlide+1);
       }
     });

**Comment by KathrynCrawford** [comment]
I'm having the same issue, in addition to the slider starting at 0 height until you do a resize. On 2.6.

<img width="1426" alt="screen shot 2017-02-23 at 11 28 42 am" src="https://cloud.githubusercontent.com/assets/10589544/23271096/ea5bdb0e-f9bb-11e6-813a-425ef50bba7a.png">
