### ISSUE TITLE
Only show image once it's fully downloaded

### ISSUE THREAD

**Issue by stemie** [woocommerce/FlexSlider#1630]
I'm using some large images as backgrounds in the slider. 

Currently on slow connections the image peels down the page as it loads and the beginning slides overlap each other. 

I only want the image to display when it's fully downloaded in the users browser. 

Surely this must be possible? 

I was doing something along the lines of `$('<img/>').attr('src', imageUrl).load(function() {...}` waiting for the image to fully download in the `before` callback. My method doesn't work though

Do you know of a way do do this?

This is what I have:

    `before: function(slider) {
         var str = slider.slides.eq(slider.currentSlide).children('.bs-flexslider-item').css("background-image")
         var res = str.split('"');

         $('<img/>').attr('src', res[1]).load(function() {
             console.log( $(this).attr('src') );
             slider.slides.eq(slider.currentSlide).children('.bs-flexslider-item').css("background-image",$(this).attr('src'))
         } );
    }`

**Comment by bbosiljcic** [comment]
You could use imagesLoaded to do this

https://github.com/desandro/imagesloaded
