### ISSUE TITLE
Flexslider stop moving when lost focus

### ISSUE THREAD

**Issue by Veecotech** [woocommerce/FlexSlider#1633]
Can anyone advise why the Flexslider will stop auto rotate whenever the browser is out of focus? E.g. when a new windows is opened on top of the website slider.

You may checked the slider in the demo(http://flexslider.woothemes.com) by open a notepad on top of the slider to notice it. The slider will stop moving.

I found one example which it is able to auto rotate even if the browsers is not in focus. – http://jsfiddle.net/paulthecoder/xtkbM/. I have checked the code and it seems to be very similar to the default flexslider code.

How do i make the slider auto rotate at all times? Appreciate if anyone could advise. Thanks.

**Comment by arashimin** [comment]
I had the same question, so I solved it as below.
Based on v2.6.3.
Delite line 9  'var focused = true;'  and,
Change line28 'methods = {};' to 'methods = {},' and,
Insert line 29 'focused = true;' 

Good Luck!

**Comment by FlamingPaw** [comment]
I have been looking for a solution to this as well, and found a temporary fix that worked for me.

On lines 1088-1092 of `jquery.flexslider.js` there is a code block that checks for window focus.
If the window is in focus, it sets the variable `focused` to true, and vice versa.
![dj0xq](https://user-images.githubusercontent.com/8386627/32390800-0ed7435e-c08d-11e7-9a76-693bb3e0f9e4.png)


On line 808 of the same file, the script checks the status of `focused` on order to decide if it should proceed to the next slide.
![gb8hz](https://user-images.githubusercontent.com/8386627/32390838-30823f18-c08d-11e7-9d69-5ca2f1089772.png)


What I did, is commented out the code block on lines 1088-1092, making the `focused` var is always true regardless of window focus.
![lbils](https://user-images.githubusercontent.com/8386627/32390879-56114116-c08d-11e7-87a9-32a955c4b9dc.png)


It would be nice to see this as a configuration option like the `pauseOnAction` and `pauseOnHover` options.
