### ISSUE TITLE
 FlexSlider does not support dynamic content?

### ISSUE THREAD

**Issue by androla10** [woocommerce/FlexSlider#1635]
Hello my name is benji, I currently work with flexslider and it is a good tool, but I have a small problem, it happens in the container of flexSlider (li), insert (div) and not (img) and how (div) change Height because the data entered in it is dynamic, I do not know how to correctly update the height of the flex-viewport div enclosing the (ul).

By the way, it only updates when you lose focus on the page itself and you re-enter.

If you do not understand this text very well, use a translation tool, excuse me.

If someone has had this problem please let me know your solution.

Greetings to all, from Peru.

Init 
$(strategyList).flexslider({
                        animation: "slide",
                        animationLoop: false,
                        slideshow: false,
                        startAt: numView,
                        smoothHeight: true,
                        keyboard: false,
                        controlNav: false,
                        directionNav: false,
                        after: function (e) {
                            self.headerDataSelected(self.headerData[e.currentSlide]);
                        }
                    });

![jhujnjk](https://cloud.githubusercontent.com/assets/11341598/23561813/dcd5249c-000d-11e7-89cd-4bd74c2f264d.png)

**Comment by swheat-dev** [comment]
unsubscribe



________________________________
