### ISSUE TITLE
Flex slider doesn't work good on window.resize and orientation change.

### ISSUE THREAD

**Issue by AnupamKhosla** [woocommerce/FlexSlider#1640]
1. Open http://flexslider.woothemes.com/dynamic-carousel-min-max.html on android or iphone. Either landscape or potrait.
2. Scroll down to carousel so that carousel-images are completely visible.
2. change orientation of device one or multiple times.  
3. You'd see number of slides in carousel don't change smoothly.  Bug!!  
4. On scrolling after orientation change the number of slides become corrected as it triggers window.resize.  
-----------------------------------------------------------  
1. Open a new empty tab in desktop browser and resize browser window smoothly to around 700px.  
2. Now click maximize window button on top right of browser. Now you can reclick that to minimize back to 700px.
3. Open http://flexslider.woothemes.com/dynamic-carousel-min-max.html and toggle between maximize and minimize window size. You'd see number of slides don't change. Although resizing smoothly the browser window would fix that, but it still is a sort of bug.

**Comment by AnupamKhosla** [comment]
I have been using flex slider in a lot of my sites and the workaround I found was to force `slider.resize` after a delay after window.resize. But this should have been inbuilt in the plugin.

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.

**Comment by tjnapster555** [comment]
@jeffikus when i resize the windows flexslider not working i am using the latest version 2.7.0
