### ISSUE TITLE
Title tag no longer appears when mouse hovers over thumbnail image

### ISSUE THREAD

**Issue by GlazerGallery** [woocommerce/FlexSlider#1648]
In the previous version of WooCommerce the image title tag popped up when the mouse hovered over a thumbnail image in the grid below the main product image. Is there a way to bring that feature back? Because I was using that.

**Comment by jeffikus** [comment]
Is this happening for you on the demo site?

**Comment by GlazerGallery** [comment]
What demo site?

**Comment by GlazerGallery** [comment]
The title tags no longer pop up when the mouse hovers over a thumbnail image. It was working in 3.0.4, but is not working in 3.0.5.
