### ISSUE TITLE
No display on animation:"slide"

### ISSUE THREAD

**Issue by darkogerguric** [woocommerce/FlexSlider#1649]
Hi, 
if I change animation to slide, I get a white screen.
There are no visible errors, the code is created (with huge height), arrows are there, code changes when clicking on arrows, but there are no images.
Using slider inside WP to create slides from ACF repeater field.
Fade animation works with no issues.
Any suggestion?
Thank you.

**Comment by rawsta** [comment]
i have the same problem in a different setup. 
intertesting that i'm not the only one with that slide problem and nobody knows why it happens.

**Comment by AliciaRamirez** [comment]
Same here.
