### ISSUE TITLE
Slider arrows not working in chrome only

### ISSUE THREAD

**Issue by xtremewriter** [woocommerce/FlexSlider#1652]
It's an older website and although not as up-to-date as I would like, the slider stopped working suddenly in chrome and I'd at least like to get it up and going again. I tried downloading and using the new JS code, but that made it disappear completely.  [www.thehendricksonhouse.com] Works fine in other browsers.   Disclosure - not a web developer, only play in the sand once in awhile. Any ideas would be much appreciated! Let me know if I can add any helpful files. Thanks!

**Comment by jeffikus** [comment]
This slider markup is definitely there, but seems like the loader is not disappearing. Can you post the code you used to start the slider?
