### ISSUE TITLE
Slider width grows when changing the page

### ISSUE THREAD

**Issue by pepelusote** [woocommerce/FlexSlider#1653]
Hi. I have a problem with a slider. Everytime I change from the browser to another program and then go back to the browser, the width of the slider increases dinamically, until it outgrows the container.

By inspecting the page I found that the translate3d is what grows, in the ul style = transform: translate3d(-1518px, 0px, 0px); That translate3d grows by 58 pixels everytime I change back and forth the browser.

I don't know if it has to do with the fact that I have 2 sliders in that page, but they are completely independent from each other. In their container div I used a different id for each one, and they both work fine and independently. Only the second one in the page is the one that is growing. But it makes no sense to me that it grows by 58 piexes since nothing has that specific size.

If I remove the second slider, the first one works fine and doesn't grow. But if I remove the first slider and leave only the second, it grows anyway. So I think there might be something else in the page or the layout that triggers that translate3d to grow. And it only happens when you change back and forth the browser.

Any Ideas about what can be causing this?

**Comment by jeffikus** [comment]
Please post here:

- [ ] 1. a link of the site, 
- [ ] 2. what browser you are using, 
- [ ] 3. what operating system as well

Thanks,
