### ISSUE TITLE
faulty animation between last slide and first slide (infinite loop)

### ISSUE THREAD

**Issue by vlrprbttst** [woocommerce/FlexSlider#1654]
Hello!
i'm using flexslider 2.6.3 and i'm encountering a weird behaviour: the slide animation between the last and first slide is faulty. here's a video: http://nimb.ws/fFTGXr

these are my settings:

```
    $(window).ready(function() {
      $('.agi-mediagallery').flexslider({
        animation: "slide",
        controlNav: false,
        slideshow: false,
        directionNav:true,
        smoothHeight: true,
        prevText: "",
        nextText: "",
        pauseOnAction: false,
        controlsContainer:".agi-mediagallery-controls"
      });
    });
```
this happens in chrome, firefox, safari (in safari less frequently). i played around with the options but nothing seem to make this "snap" go away. not sure what to do.
thanks! 👍

**Comment by jeffikus** [comment]
Hi there

Will test this and get back to you as part of the 2.7.0 release cycle.
