### ISSUE TITLE
this website is using FlexSlider but why it is different ?

### ISSUE THREAD

**Issue by ibraheemhsn** [woocommerce/FlexSlider#1658]
Hello, 
this is not issue, and I am sorry as I may post off-topic here, 
this website https://www.testo.com/en/testo-623/p/0560-6230#lg=1&slide=0
is using FlexSlider but obviously it is different look and feel from the standard demo, 
can I make FlexSlider works and looks like above website ? 
Thanks

**Comment by vlrprbttst** [comment]
of course you can, just "hack" flexslider's css

**Comment by simonrcodrington** [comment]
ibraheemhsn - You'll need to adjust the CSS to get it to whatever visual design you're after.  Start with the base CSS provided in flexslider and override it as needed. 

Certain things like the slide container and each slide should be left as they are (as the plugin calculates widths and positioning) but overall you can adjust it until it suits your needs.

**Comment by ibraheemhsn** [comment]
@simonrcodrington and @vlrprbttst  Thank you , modification done like you advised ..
