### ISSUE TITLE
Flexslider 2.5.0 disappeared after changing page title

### ISSUE THREAD

**Issue by vciulei** [woocommerce/FlexSlider#1659]
Hi all, 
I'm pretty new to CSS and back-end coding in general so I apologize in advance for any inconsistencies in my descriptions.
So I have flexslider v2.5.0 installed in my WP website ( www.thealoftgroup.com) but no flexslider plugin in the actual WP. Recently I have updated the title of my homepage and the slider has since disappeared. I changed the title of the page back to its previous name but the slider is not there anymore. This is the second time it has happened, the first time I resolved it by restoring the website from an older version. I am sure the change in page title is what is causing the slider to disappear. the slider appears on the home page only. Here's a snapshot of what it looked like before. Any help is greatly appreciated!
![slider](https://user-images.githubusercontent.com/29777378/27689263-f6c2b068-5cdd-11e7-825d-71f0efbf0868.png)

EDIT: Am trying to solve this but to no avail. @Tyler Smith do you have an idea?

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
