### ISSUE TITLE
Disable flexslider grow

### ISSUE THREAD

**Issue by JosephP91** [woocommerce/FlexSlider#1660]
Hi, I would like to display different size images using flexslider. When an image is taller than another, the entire flexslider resize itself and I would like to disable this effect. Is it possible to display every image without resizing the container? Thank you

**Comment by jeffikus** [comment]
You can fix the height, but then you would have the background showing where the "white space" areas are, if that's ok then sure, can you pop a snippet of code that you are using so I can take a look?

**Comment by JosephP91** [comment]
Hi @jeffikus 
I solved using the following style on the img item:

```css
style="width: auto; height: auto; max-height: 480px; display:block; object-fit: cover; margin: 0 auto;"
```
