### ISSUE TITLE
Line height problem with bootstrap 4.0

### ISSUE THREAD

**Issue by jmaicon** [woocommerce/FlexSlider#1661]
Hi, thanks for the great plugin, I always have to add line-height: 40px on the direction nav 'a's for them to appear complete on the screen, otherwise it will show just about 80% of its complete height, I'm guessing this might be a problem with bootstrap's 4.0 reset settings, and I don't think that adding this rule will cause any other problems at all.. just a tip, thanks again.

**Comment by jeffikus** [comment]
Hi, that's an interesting scenario, do you have a URL where I can see this at? Or a code snippet.
