### ISSUE TITLE
Mysterious margin being added after blur or scrolling on mobile

### ISSUE THREAD

**Issue by BenRacicot** [woocommerce/FlexSlider#1662]
I am using lastest Flexslider and have the strangest issue where whenever I scroll on mobile sized screens the `<li>` grows by 30px automatically (please see code)

I found this when tracking down why the slider seems to jump when scrolling on mobile leaving the slides slightly offset like this:
initial load:
![screen shot 2017-07-31 at 2 44 04 pm](https://user-images.githubusercontent.com/1815385/28792933-5ab656da-75ff-11e7-8145-74b31478139d.png)
```
<li class="slide flex-active-slide" style="width: 245px; margin-right: 0px; float: left; display: block;">
    <a href="/UtilidataCom/leaders/">
        <div class="image" style="background: transparent url('/UtilidataCom/wp-content/uploads/2017/02/Leadership_CJ_Large.jpg') no-repeat center center;background-size:cover;"></div>

    </a>
</li>

```

After scrolling on iPhone (Chrome or Safari) or clicking out of the screen and back in when emulating iPhone with dev tools.
![screen shot 2017-07-31 at 2 43 35 pm](https://user-images.githubusercontent.com/1815385/28792934-5ab7c54c-75ff-11e7-909e-c8c844bf68dc.png)

```
<li class="slide flex-active-slide" style="width: 275px; margin-right: 0px; float: left; display: block;">
    <a href="/UtilidataCom/leaders/">
        <div class="image" style="background: transparent url('/UtilidataCom/wp-content/uploads/2017/02/Leadership_CJ_Large.jpg') no-repeat center center;background-size:cover;"></div>

    </a>
</li>
```

The slide contains a div using a background-image. Perhaps that's the cause? slides with `<img>` do not have this issue.
Oh forgot to mention, this is live at https://utilidata.com/leadership/ (but use dev tools responsive emulator because flexslider is only init on mobile sized screens)

**Comment by AnupamKhosla** [comment]
I couldn't find the the slider demo working on your live page https://utilidata.com/leadership/  

I think your css margin rule is overridden by more specific selectors. It could be when `after` event fires some class is added to `flexslider` parent `div`. It would be better to replicate the demo on stackoverflow.
