### ISSUE TITLE
v2.6.4 major responsive issue

### ISSUE THREAD

**Issue by Soullighter** [woocommerce/FlexSlider#1665]
Ok, I spend 4 hours to figure it out what is a problem on my side, but basically it was flexlider.js faulth.
v2.6.4 have a major issue in responsive when window is scaling, you can see it in simple demo/index.html . When I put v2.6.1 ( luckily I have it on my prev project ) everything is working fine.

**Comment by theenoahmason** [comment]
I can confirm 2.6.4 is no longer resizing slides according to window width. All slides are the size they were when loaded at all times, essecntially forcing carousel behavior... however trying to override this by setting itemWidth, minItems: 1, maxItems: 1 (for example) has 0 effect.

This release is so broken it is unusable.

**Comment by simonrcodrington** [comment]
This is **significantly** broken and as it stands now is entiely unuseable.

The recent changes in **2.6.3 / 2.6.4** have stuffed up the resize calculations and makes each item inside the fle slider non responsive. 

I've spent hours trawling through dozens of files, libraries and other elements trying to find out what was causing flexslider to not work responsively. Any calls to manually hook into the resize event to call the resize method of the slider would cause recursion.

I compare my slider against the slider used on the demo site and it was identical, I couldn't figure out how the demo's slider would resize but mine would not. 

It was only when I looked directly at the code the demo website is using did I find it uses version 2.6.2 and that version works. The download button on the page gives you version **2.6.4** which has the issue.  Using the older version has resolved my issue and everything is right in the world. 

I'm amazed that a version was released that broke a fundamental part of the plugin. In future I will have to stick to old version of the library as I can't be sure that new ones will function as intended.

**Comment by olimorris** [comment]
Do they even have any tests for this?!

**Comment by laurentdinclaux** [comment]
I can confirm: it will not adapt anymore to the window size when it gets resized. It completely breaks when toggling between landscape and portrait modes on handsets.

2.6.2 is the last working version

**Comment by ligget** [comment]
bug is caused by this change:

         // FADE&&SMOOTHHEIGHT || SLIDE:
-        if (!fade || (fade && slider.vars.smoothHeight)) { $(window).bind("resize orientationchange focus", methods.resize); }

+        if (!fade || (fade && slider.vars.smoothHeight)) { $(window).bind("resize orientationchange focus", methods.resize()); }


"methods.resize()" should be changed back to "methods.resize" without "()"

**Comment by jeffikus** [comment]
Thanks all, I know about this, I'm working on it. I understand your frustration and I just ask for patience while I attend to all the issues.

**Comment by Soullighter** [comment]
We are here to point on problems, so you don't need to dig it by yourself ;-)
In the end, you help us a lot with your time to make this plugin, that is why we give you a friendly feedbacks

**Comment by jeffikus** [comment]
@Soullighter :) thanks man, messages like that make it all worthwhile :)

**Comment by jeffikus** [comment]
But seriously I know this has taken a while, I do apologize!

**Comment by Soullighter** [comment]
Hey, don't worry. I think loth of the community don't judge you at all. Hey, it's Git, we all know how to take prev versions ;-) Keep it cool, and fix the problem man :-D

**Comment by BenRacicot** [comment]
@jeffikus hey Jeff, any word on an update for 2.6.5+?

**Comment by DeepBlue1** [comment]
I had problem when resizing the window images width and positions get messed up,
changing to 2.6.1 fixed the problem! I spent hours trying to find a solution.

**Comment by IntrepidRealist** [comment]
Thank you to all who have gone before me. I only spent 45 minutes before finding this post. Using Flexslider from an old project just saved me. I just swapped out the js file.

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
