### ISSUE TITLE
Cannot pause animation via play/pause button in IE11

### ISSUE THREAD

**Issue by FcrbPeter** [woocommerce/FlexSlider#1676]
The play/pause button is not fully function on mouse click in IE1.

When I make a mouse down event on the pause button, it changes to play button. However, after the mouse up, the play button changes to pause again. Btw, I can pause the animation when I press the pause button and move outside the button area.

I am thinking about the button state changed twice on both mouse down and up events.

**Comment by FcrbPeter** [comment]
After some tracing, I found that there is a MSPointerDown event fired.
It seems always pause the animation of the slider.

 ```
function onMSPointerDown(e) {
	e.stopPropagation();
	if (slider.animating) {
		e.preventDefault();
	}else{
		slider.pause();
		el._gesture.addPointer(e.pointerId);

		...
	}
}
```

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.

**Comment by taeyoun** [comment]
It still persist. I tested in IE 11.

**Comment by taeyoun** [comment]
Submitted a pull request https://github.com/woocommerce/FlexSlider/pull/1708
