### ISSUE TITLE
Hello, great god，Dot problem

### ISSUE THREAD

**Issue by wangyi1998** [woocommerce/FlexSlider#1680]
FlexSlider  directionNav question。
I want to set the position of the dot。How do you do that。

========================
你好，大神，我想问下关于圆点位置的问题，
如果我要把圆点向上移动，该怎么写呢。

![snip20171115_1](https://user-images.githubusercontent.com/17868020/32821158-9f9897a4-c997-11e7-9787-74f98710956d.png)

**Comment by jeffikus** [comment]
Hi there. You can change the CSS here https://github.com/woocommerce/FlexSlider/blob/master/flexslider.css#L199 to bottom: 10px; and that should do what you need.
