### ISSUE TITLE
Carousel skipping images when set to animation slide

### ISSUE THREAD

**Issue by indeep-singh-2812** [woocommerce/FlexSlider#1681]
Hi, I am facing a issue using flexslider carousel that when animation is set to slide and autoloop property is set to true, and after page load, whenever I click the image thumbnail for next image, it skips the next image and displays the one after that. 
For example, suppose I am on first image in carousel , I click on the image thumbnail for next image then the second image gets skipped and the third image is shown.
This issue however works fine when I do next using navbar icons or when animation is set to fade.

I have checked with flexslider latest library version 2.6.4, and this issue is reproducible with this version as well. 

Any help/suggestion would be highly appreciated.

**Comment by jeffikus** [comment]
Hi there. I released 2.7.0 last week. Please update and let me know if the issue persists.
