### ISSUE TITLE
Flexslider width calculation issue: slide partially showing next slide

### ISSUE THREAD

**Issue by BenRacicot** [woocommerce/FlexSlider#1689]
Trying to understand a bug within my Flexslider implementation. The bug resides at [https://utilidata.com](https://utilidata.com) where upon load (sometimes) a small part of the next slide is being displayed.

![screen shot 2017-12-04 at 2 24 21 pm](https://user-images.githubusercontent.com/1815385/33571698-dba3c022-d8fe-11e7-8e2b-0eba761ba57a.png)

In this case the width calculation is only showing 1px of the image to the right. However some browsers have shown up to 20-30px-ish. Also it should be mentioned that this issue is often seen when the browser is resized in addition to `onload`.

Has anyone come across wonky slide-width calculations? Same in 2.6.1-2.6.4.

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
