### ISSUE TITLE
Product images: want to disable zoom on magnifier and have it only open lightbox

### ISSUE THREAD

**Issue by GlazerGallery** [woocommerce/FlexSlider#1692]
We are finding that some customers never realize when they are on a Product Page that they can open a lightbox and page through all the images in the lightbox, because if you put the cursor on the magnifier icon, it hovers over a magnified version of the image, and that looks like the only possibility to them. We'd like to turn off that hover/enlarge feature so that the only thing that happens when you click the magnifier it _only_ opens the lightbox. It's important to us because there is caption info that only appears in the lightbox. If the alt text info popped up when you were hovering on a thumbnail or main image that would be great, too. These are things that went away with version 3 and that we still wish we could get back somehow.

**Comment by jeffikus** [comment]
Hi there. Are you using WooCommerce? If you are, you need to log the issue in the WooCommerce repository here -> https://github.com/woocommerce/woocommerce/issues/new
