### ISSUE TITLE
ReferenceError: SyntaxHighlighter is not defined

### ISSUE THREAD

**Issue by myndt** [woocommerce/FlexSlider#1694]
I am using next code:

<script src="js/masterslider/jquery.easing.min.js"></script>
<script src="js/masterslider/masterslider.min.js"></script>
<script type="text/javascript">
(function($) {
 "use strict";

var slider = new MasterSlider();
 slider.setup('masterslider' , {
     width: 1400,    // slider standard width
     height:720,   // slider standard height
     space:0,
	   speed:45,
     fullwidth:true,
     loop:true,
     preload:0,
     autoplay:true,
	 view:"basic"
});
// adds Arrows navigation control to the slider.
slider.control('arrows');
slider.control('bullets');

SyntaxHighlighter.all();

})(jQuery);
</script>

where I am getting an error:  ReferenceError: SyntaxHighlighter is not defined
Whats wrong? Pls help...

**Comment by Nisarg1792** [comment]
```
<script src="js/masterslider/jquery.easing.min.js"></script> 
<script src="js/masterslider/masterslider.min.js"></script> 
<script type="text/javascript"> 
  (function($) { "use strict"; 
       var slider = new MasterSlider();
           slider.setup('masterslider' , { 
             width: 1400, // slider standard width 
             height: 720, // slider standard height 
            space: 0, 
            speed: 45,
           fullwidth: true,
           loop: true, 
          preload: 0, 
          autoplay: true,
          view: "basic"
  }); // adds Arrows navigation control to the slider. slider.control('arrows'); slider.control('bullets'); 
  SyntaxHighlighter.all(); 
 })(jQuery); 
</script>
```
