### ISSUE TITLE
Resize doesn't work in 2.6.4, works in 2.6.3

### ISSUE THREAD

**Issue by Frank-Steiner** [woocommerce/FlexSlider#1695]
Hi,
using flexslider 2.6.4 the pictures don't resize when the browser window resizes, only the frame showing the pics does. Thus the pics either get cropped or part of the next pic is shown on the right border.
In 2.6.3 it works fine and comparing the two showed that in line 148

`       if (!fade || (fade && slider.vars.smoothHeight)) { $(window).bind("resize orientationchange focus", methods.resize()); }`

had to changed to 
`        if (!fade || (fade && slider.vars.smoothHeight)) { $(window).bind("resize orientationchange focus", methods.resize); }`

I've no idea it that destroys sth. else like resize on orientation changes etc, on my desktop browsers it works fine.

Just to let you know...

cu,
Frank

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.

**Comment by Frank-Steiner** [comment]
The problem is solved with the update :-) Thanks a lot!
