### ISSUE TITLE
In Firefox, RTL is not working.

### ISSUE THREAD

**Issue by titechnologies** [woocommerce/FlexSlider#1699]
I had the issue in development url.
But when checking the demo, there also we can see the same issue.
http://flexslider.woothemes.com/index-rtl.html

**Comment by webkees** [comment]
Same issue here. On a running website flexslider suddenly doesn't show the sliedes anymore (disappeared to the right off screen). Firefox 58.0.
In Google Chrome everything is okay. Have updated the package after you announced a fix some month ago, but this new package still has this issue.

**Comment by aleksanderd** [comment]
same here. any news?

**Comment by alexvibealex** [comment]
same issue here. any quick fix for this ? When its going to be reolve?

**Comment by NabiKAZ** [comment]
I test on `FireFox 64.0.2 (64-bit)`
URL: http://flexslider.woothemes.com/index-rtl.html
![image](https://user-images.githubusercontent.com/246721/51711568-b0a3d200-2041-11e9-8b55-5f51522808d3.png)
Seem used `FlexSlider v2.7.0` (latest version is 2.7.1 for now)
And so seem didn't included `flexslider-rtl.css` file. and this file included in the (http://flexslider.woothemes.com/asnavfor-rtl.html) page, But return `404 Not Found`.
see: http://flexslider.woothemes.com/css/flexslider-rtl.css
I thinks the demo web page must be updated.
