### ISSUE TITLE
Deprecated jQuery 3.0+ functions

### ISSUE THREAD

**Issue by jonyo** [woocommerce/FlexSlider#1716]
I am working on upgrading to latest version of jQuery, using the jquery-migrate plugin to help.  Below are a list of functions that the migration gave warnings for:

* jQuery.fn.blur() event shorthand is deprecated
* jQuery.fn.focus() event shorthand is deprecated
* jQuery.fn.delegate() is deprecated
* jQuery.fn.bind() is deprecated
* jQuery.fn.hover() is deprecated

There may be other deprecated or removed methods, those are the ones that come up with my use of the flex slider and using the jquery-migrate plugin.

**Comment by DenisLabrecque** [comment]
This is still a problem that needs to be fixed. Upgrading to jQuery 3.5 and see issues with `$.blur()` and `$.focus()`
