### ISSUE TITLE
how to create thumbnails not in the slider

### ISSUE THREAD

**Issue by murgnis** [woocommerce/FlexSlider#1721]
how to create thumbnails not in the slider
but thumbnails slightly bigger (in line 4) and next sorts in a new line, not Slide

currently: [https://ibb.co/cuo5OJ](https://ibb.co/cuo5OJ)
but I want [https://ibb.co/diB3Ay](https://ibb.co/diB3Ay)

if the pictures are even more, then new rows are forming

is it possible? if yes, then how 
thank you very much

**Comment by jeffikus** [comment]
Hi there, have you tried the example code for this demo? http://woocommerce.github.io/FlexSlider/thumbnail-controlnav.html you can find the example code in https://github.com/woocommerce/FlexSlider/blob/master/demo/thumbnail-controlnav.html
