### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by electroheadfx** [woocommerce/FlexSlider#1724]
Hey,
When I resize the windows, flexslider doesn't always find the good size:
http://host.electroheadfx.fr/efxbox/laurent/Capturedecran2018-06-20a10.09.53.png

is it possible at windows event to re-init the bxslider like it was created in fly in JS ?
else not is it possible to destroy flexslider then I can re-construct on the new windows ?

thanks

**Comment by RichardHuynh3004** [comment]
Same problem with mobile, the first init calculate width not correct
