### ISSUE TITLE
Flexslider 1.8 link is broken

### ISSUE THREAD

**Issue by philipca** [woocommerce/FlexSlider#1726]
I wish to use flexslider in a website whose design is currently compatible with many older browsers (such as IE8) as well as iOS and Android, so I clicked the link you give to download "flexslider 1.8" under "GENERAL NOTES" but the link is broken!

Please tell me how I can download flexslider 1.8

**Comment by jeffikus** [comment]
Hi there, I would not recommend nor would we support using such an old version of Flexslider. If the current version does not work in a specific browser, please let me know and we can take a look if it is indeed a bug.
