### ISSUE TITLE
Not working with latest jquery

### ISSUE THREAD

**Issue by ihaiderx** [woocommerce/FlexSlider#1729]
The slider does not display with jQuery 3.1.0 that my website has built into it. It does work when I add jQuery 1.6.2, but I'd prefer not to load two jQuerys on my website. Thank you!

**Comment by gkirthiv** [comment]
hi ihaiderx,

can you try with document.ready instead of window.load?

thanks

**Comment by andreyshr** [comment]
I have hit the same bug. The solution from the document.ready fixed it. Thanks!

**Comment by ihaiderx** [comment]
I'm still having the same issue even after using document.ready, but I think that has to do with the fact that the built-in jQuery in my Shopify theme is being called with 'async' or 'defer'. Is there a way to make flexslider work with a async or deferred jQuery?

**Comment by gkirthiv** [comment]
if you use 'defer', call the 'flexslider' by using setTimeout(). Also use 'defer' in your flexslider like,
`<script defer src="../jquery.flexslider.js"></script>`.
