### ISSUE TITLE
FlexSlider 2 in Windows 10 (Using IE11)

### ISSUE THREAD

**Issue by colonieweather** [woocommerce/FlexSlider#1732]
I downloaded the latest version of FlexSlider (2.7.1). In my testing, I observed that the fade effect is not working when using Internet Explorer 11 on Windows 10. I am using jQuery 3.3.1. 

The latest FlexSlider version I found the fade effect to work is version 2.2.0 with jQuery 3.3.1.

**Comment by rhazor** [comment]
Can confirm, having same issue.

**Comment by MrtianYs** [comment]
you can set the option of touch to false. the fade effect is working. or you can see the source code.  line 861.  add css transition. the fade effect is alse working
