### ISSUE TITLE
Set height to that of tallest slide?

### ISSUE THREAD

**Issue by badfeather** [woocommerce/FlexSlider#174]
When using horizontal and vertical images and having any content beneath the slider in the design, the height of the Flexslider changes to that of each slide, which causes the content beneath it to jump up and down. Is there any way to disable this, and instead have it maintain the height of it's tallest slide?

**Comment by JMarqz** [comment]
I'm using the @ghost solution, but for some reason not always is setting the height of the tallest image. When I reload my site, some times, take another height that is not the tallest. Somebody has the same problem? Somebody can help me? Thanks!

**Comment by stan333** [comment]
I find another solution, consisting of returning a div within the image in background instead of a < img >. Then I applied "background-size:cover;" to the div.

So in the code, I replace :
```
if ( (function_exists( 'has_post_thumbnail' )) && ( has_post_thumbnail() ) ) :
. get_the_post_thumbnail( get_the_ID(), 'activello-slider' ) .
```
for :
```
if ( (function_exists( 'has_post_thumbnail' )) && ( has_post_thumbnail() ) ) :
$feat_image_url = wp_get_attachment_url( get_post_thumbnail_id() );
echo '<div class="flexslideimg" style="background-image:url('.$feat_image_url.');"></div>';
```

**Comment by AdalDesign** [comment]
For some reason @ghost's solution didn't work out of the box for me... so I edited it to be more robust for my specific needs and came up with this (for the latest version of FlexSlider):

	jQuery(document).ready(function() {

		setTimeout(function(){  // because the elements are created by JS, we need to wait before modifying them
			// Set fixed height based on the tallest slide
			jQuery('.flexslider').each(function(){
				var sliderHeight = 0;
				jQuery(this).find('.slides > li > a > img').each(function(){
					slideHeight = jQuery(this).height();
					if (sliderHeight < slideHeight) {
						sliderHeight = slideHeight;
						console.log( sliderHeight );
					}
				});
				jQuery(this).css({'min-height' : sliderHeight});
			});
		}, 4000);
	});

**Comment by cyclone747** [comment]
Use these function 
end: function() {fixFlexsliderHeight();}
start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
    before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
    after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
    end: function(){},              //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
    added: function(){},            //{NEW} Callback: function(slider) - Fires after a slide is added
    removed: function(){},           //{NEW} Callback: function(slider) - Fires after a slide is removed
    init: function() {}

**Comment by Soullighter** [comment]
@AdalDesign and @cyclone747 combination
Here most important thing is to pass argument **slider** inside `init` function
Don't forget to add in CSS `transformY: -50%` to the `img` tag.

`jQuery(document).ready(function($)

 {
     $('.flexslider').flexslider({
       init: function(slider) {

        var sliderHeight = 0;

        slider.find('.slides > li > a > img').each(function(){

          slideHeight = $(this).height();

          if (sliderHeight < slideHeight) {
            sliderHeight = slideHeight;
          }

        });
        slider.css({'min-height' : sliderHeight});
        slider.find('.slides > li > a > img').each(function(){
          $(this).css({'top' : (sliderHeight / 2)});
        });
       }
     });
});
`
