### ISSUE TITLE
animation: "fade" doesn't work anymore

### ISSUE THREAD

**Issue by horacegrant** [woocommerce/FlexSlider#1741]
i am using the latest version 2.7.1 and the fade animation doesn't work anymore (in chrome and firefox). the slider simply stays white. what could be the reason for this? i found some older threads about messed up css3 transitions but those threads seem to be quite old.

**Comment by contempoinc** [comment]
+1 to this none of the options work, like vertical, duration, speed, etc…believe its an issue with the latest version of jQuery haven't had a problem prior for 2+ years on v2.7.0
