### ISSUE TITLE
RTL : Slider starts with wrong image

### ISSUE THREAD

**Issue by rnivash** [woocommerce/FlexSlider#1748]
if I enable RTL, slider starts with last image in the array instead of the first one. This issue is clearly visible when manual controls are in use and each buttons are linked wrong image **(i-1)**. I am able to reproduce this issue in demo too.

In asnavfor-rtl.html demo file, 
it starts with image "Adventurer Caramel" instead of the first image "Adventurer Cheesecake Brownie".

**Comment by rnivash** [comment]
http://flexslider.woothemes.com/asnavfor-rtl.html

![image](https://user-images.githubusercontent.com/503731/50444894-11e86080-0931-11e9-8a2d-79fb030ffed6.png)

**Comment by acrolink** [comment]
I am experiencing the same issue. I have three slides, goes 3rd, 1st, 2nd..
