### ISSUE TITLE
Next and previous buttons are cropped

### ISSUE THREAD

**Issue by Xerbo** [woocommerce/FlexSlider#1752]
I'm in creating electron app and am using flexslider from npm and have discovered a problem with the positioning of the next and previous buttons.
![Previous](https://user-images.githubusercontent.com/23143405/53107810-c49dff00-352d-11e9-9eed-085053554a20.png)
![Next](https://user-images.githubusercontent.com/23143405/53107814-c5cf2c00-352d-11e9-8f27-46ecfeea2161.png)
I am on a linux system with:
kernel: 4.15.0-45-generic
NPM: v3.5.2
node.js: v8.10.0
electron: v0.35.6

This may be specific to me but can be fixed easily with the following css:
```
.flex-direction-nav a:before{
  line-height: 1;
}
```

**Comment by cworth-gh** [comment]
Thanks. I had the same bug and the workaround given here fixed things for me as well.

**Comment by laryn** [comment]
Problem exists for me as well and the fix takes care of it. I have submitted it as a PR here:

 - https://github.com/woocommerce/FlexSlider/pull/1796
