### ISSUE TITLE
animation: "slide" causes component disappear after click video contextmenu.

### ISSUE THREAD

**Issue by aboveyunhai** [woocommerce/FlexSlider#1771]
Issue regenerate: 
https://jsfiddle.net/7m259pjx/1/

animation:"fade" works normal when click the context menu of h5 `<video>` tag
but video will display none in animation:"slide"

**Comment by seanmortimer** [comment]
For anyone else coming across this, adding `video: true`  to the slider options fixed it for me.   

![image](https://user-images.githubusercontent.com/60672606/102554230-98982a00-4081-11eb-95b9-5ac79497145b.png)  


I found the option here:
https://gist.github.com/warrendholmes/9481310
