### ISSUE TITLE
$( '.flexslider' ).flexslider({ is not running occasionally

### ISSUE THREAD

**Issue by c-dicle** [woocommerce/FlexSlider#1793]
Hi all,

As of this week, we started to have issues with Flexslider. Occasionally, the initialization is not firing. 

It is really occasional and there is no warning or error in the console when it is not firing. 

The script is inserted properly as on load.

It might be cache related as generally during the first load it is fine but after a refresh of the page it is gone.

Any suggestions?

Thank you.
Best,
C.

**Comment by NickSutton** [comment]
Seeing this also, well, it's been reported to me but am unable to replicate it.
