### ISSUE TITLE
Using the control nav does not reset the slide timer

### ISSUE THREAD

**Issue by petelopez** [woocommerce/FlexSlider#181]
Using the 7000ms time between slide changes, if I wait 5000ms and use the control nav to switch to a different slide it will go to the next slide in 2000ms.

**Comment by mersenarabzadeh** [comment]
It's not work for me :( i think i put values of function wrong.
this is the website, you can see slideshow: http://johnhardyperfume.com/home.php

class of the slider is "slides".
this is js file: http://johnhardyperfume.com/js/jquery.flexslider-min.js
would you help me please?
