### ISSUE TITLE
Calling .flexslider() when target is hidden.

### ISSUE THREAD

**Issue by davekiss** [woocommerce/FlexSlider#182]
Flexslider 2 is a godsend.

I have my slider behind a tab while using Twitter bootstrap, and when I switch to that tab, the slider doesn't function as expected. Is there any way of making sure that this conflict doesn't occur?

**Comment by rajeshaspl** [comment]
Hi,
I am using flexslider with In Drupal horizontal tabs.
I have loaded slider and carousel from different blocks and assign to horizontal tab.
the slider working in desktop it's fine. But we should open the slider in mobile/iphone that first time loaded fine when change the orientation it could not work in responsive layout.

please could you help me.
slider id is #flexslider-4
and carousel id is #flexslider-5.

here is javascript code i am using when window load and horizontal tab clicked.

jQuery('#flexslider-5').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 100,
    itemMargin: 14,
    asNavFor: '#flexslider-4'
  });
   
  jQuery('#flexslider-4').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#flexslider-5"
  });

**Comment by PerchHero20** [comment]
Hello,
I just inherit a flexslider from another developer.
The slider has 6 images rotating.
The think that happens is that if I have multiple tabs with the page open or if I minimize browser and I restore it after, the images starts to rotate very fast as if they want to catch with the time they were hidden. I think that this has something to do with jquerry not running when hidden?
Anyone has any ideas?

**Comment by JamShady** [comment]
Thanks @davekiss for that solution

**Comment by fricks** [comment]
I'm having issue in first bs tab using flexslider. Only after click on the second tab the slider is actived.
Anyone can help me out? Thanks

````
$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
  //console.log('showing tab ' + e.target); // Active Tab
  //console.log('showing tab ' + e.relatedTarget); // Previous Tab
  //alert("");

  $('#carousel').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 140,
    itemMargin: 5,
    asNavFor: '#slider'
  });

  $('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel"
  });

});

$(window).load(function(){
  initflexsliders();
});


function initflexsliders(){

  $('#carousel2').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 140,
    itemMargin: 5,
    asNavFor: '#slider2'
  });

  $('#slider2').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel2",
  });

  $('#carousel3').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 140,
    itemMargin: 5,
    asNavFor: '#slider3'
  });

  $('#slider3').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel3",
  });

  $('#carousel4').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 140,
    itemMargin: 5,
    asNavFor: '#slider4'
  });

  $('#slider4').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel4",
  });

  $('#carousel5').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 140,
    itemMargin: 5,
    asNavFor: '#slider5'
  });

  $('#slider5').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel5",
  });

}
````

**Comment by shails** [comment]
I have two flexsliders on a page , The first one is a main carousel and the other one is inside the Bootstrap Modal . 

The slider inside the modal  doesnt work when the animation is set to slide ; all the text and slides overlap and a width of 0 is set automatically . If the browser is resized then the slides revert to their correct sizes so,and it only seems to happen on the initial page load.
    `$(window).load(function() {
     /************** FlexSlider *********************/
       $('#myCarousel').flexslider({
        animation: "fade",
        directionNav: false,
        controlNav: false //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage

        });
       $('#slider').flexslider({
        animation: "slide",
        directionNav:true

    
        });
   });`

**Comment by liangrongze** [comment]
@shails

**Comment by nrvnm** [comment]
Hey guys, `$('.flexslider').resize();` did the trick for me when slider didn't init inside hidden tab. But for some reason it only worked after the second call, so my solution is:

$('.flexslider').resize();
$('.flexslider').resize();

Weird eh?

Also if you work your way through and do some arrangement and restyling and use `opacity: 0;` instead of `display: none;` it also works well. Slider does init this way, while the tab is not visible.

**Comment by nickmeagher** [comment]
@dtbaker Thank you for the fix! This fixed my problem of initially having the parent div set to display: none; and I have 3 sliders on the same page.

Specifically this line: `$($this.attr('href')).find('.flexslider').data('flexslider').resize();`

Thank you!

**Comment by homarb** [comment]
I was still having the problem but this sorted it out:
```
$('#myTab').on('shown.bs.tab', function () {
    $(window).trigger('resize')
})
```
I hope this helps

**Comment by HDaghash** [comment]
this is work for me :+1: $($panel + ' div').data('flexslider').setup();

**Comment by manuelvarguez** [comment]
Fix for use FlexSlider 2 with Bootstrap 3 Tabs
$('.nav-tabs a').click(function(){
            $(this).tab('show');
            $('.flexslider').resize();
        });

**Comment by sonill** [comment]
Thank you @manuelvarguez . your solution worked for me.

**Comment by qaisar-jat** [comment]
Hi,

Trying to load flexslider in bootstrap modals. They are many on a single page, the modal boxes load fine on each click. But flexslider only loads for a very first modal trigger, which also takes a few seconds to load. Any help? Following is the code.

jQuery('.modal').on( 'shown.bs.modal', function() {
	jQuery('.flexslider').resize();
});
$(window).load(function(){
	// The slider being synced must be initialized first
	jQuery('#carousel').flexslider({
		animation: "slide",
		controlNav: false,
		animationLoop: false,
		slideshow: false,
		itemWidth: 160,
		itemMargin: 5,
		asNavFor: '#slider'
	});
	jQuery('#slider').flexslider({
		animation: "slide",
		controlNav: false,
		directionNav: false,
		animationLoop: false,
		slideshow: false,
		sync: "#carousel"
	});
});

**Comment by dboutote** [comment]
I don't know if this will help anyone.  But the following worked for me.
```
$('.flexslider').each( function(){
    var $this = $(this);
    var $parent = $this.closest('.tab-pane');
    if( ! $parent.length ){
        $this.flexslider({
            animation  : "slide",
            slideshow  : false,
            controlNav : false
        });
    }                
})

$('a[data-toggle="tab"]').on('hide.bs.tab', function (e) {
    $('.flexslider').flexslider({
        animation  : "slide",
        slideshow  : false,
        //controlNav : false
    });
})
```
Since we use multiple sliders throughout the site, and some are hidden in Bootstrap tabs what we're basically doing is checking on each slider to see if it's in a tab.  If it is, we do nothing.  If it's not, we instantiate it.

Then, when Bootstrap fires its `hide.bs.tab action, we initialize the flexslider (if any) within the tab.

**Comment by FaramarZHidden** [comment]
hello, i have same problem with flexslider in tabs. when change tabs, width set to 21px
and direction nav not working on tab 2.
tab 1 is working correctly.
 
that's my js code:

```
$(window).load(function() {
  $('.flex1.flexslider').flexslider({
    animation: "slide",
    animationLoop: false,
    itemWidth: 210,
    itemMargin: 5,
    minItems: 1,
    maxItems: 3
  });
  $('.flex2.flexslider').flexslider({
    animation: "slide",
    animationLoop: false,
    itemWidth: 210,
    itemMargin: 5,
    minItems: 1,
    maxItems: 3
  });
});
```
html :

```
<a href="#" class="list-group-item active text-center"><span>tabs 1</span></a>
<a href="#" class="list-group-item text-center"><span>tabs 2</span></a>

<div class="bhoechie-tab-content active">
	<div id="slider" class="flex1 flexslider amazing_p">
		<ul class="slides">
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
		</ul>
	</div>							
</div>

<div class="bhoechie-tab-content">
	<div id="slider" class="flex2 flexslider amazing_p">
		<ul class="slides">
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
		</ul>
	</div>							
</div>

```
anyone can help me to fix that ?

**Comment by sajalaspl** [comment]
Hi
Change the "slider" id to slider123 of second tab then it works for you.

div class="bhoechie-tab-content">
	<div id="slider123" class="flex2 flexslider amazing_p">
		<ul class="slides">
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
			<li class="col-md-4"> bla bla bla bla </li>
		</ul>
	</div>							
</div>

**Comment by FaramarZHidden** [comment]
thanks but not working ..

**Comment by cro55er** [comment]
Hi, all! It's all simply!

In css dont use display: none; for tab!

 use this code and all work perfectly!

.tab {
	height: 0px;
	opacity: 0;
	overflow: hidden; (optial - needs for slow animation transition )
	transition: 0.6s;
}

.tab_active {
	height: auto;
	opacity: 1;
}

**Comment by atempel** [comment]
For me, best solution was to do as @frequent said. Just initialize the slider when the tab or link to show the slider is clicked:

```
$('SELECTOR/CLASS_FOR_LINK').click(function(){
    $('ID/CLASS_FOR_SLIDER').flexslider({
      // your options
    });
});
```
Only down-side is that if your website is already js heavy (scroll binds, window change binds, etc) the slider might flick a bit before rendering completely.

**Comment by tarekabosaif** [comment]
Hi everyone i have the same problem and my code here is 

    // $(function(){
    //   SyntaxHighlighter.all();
    // });
	$('a[data-toggle="tab"]').click(function() {
		setTimeout(function() {
			$(document).trigger('resize');
		}, 0);

		setTimeout(function() {
			$(document).trigger('resize');
		}, 2)
	});
	
    $(document).ready(function(){
      $('#carousel').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 260,
        itemMargin: 5,
        asNavFor: '#slider'
      });

      $('#slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        sync: "#carousel",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });

      $('#carousel2').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 260,
        itemMargin: 5,
        asNavFor: '#slider2',
      });

      $('#slider2').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        sync: "#carousel2",
		start: function(slider){
          $('body').removeClass('loading');
		// console.log("im broken");
        }
      });
	  
	});

i try everything you said but i don't know why the slider working when i click on the tab twice, 
please answer i need to solve it. :(

**Comment by atempel** [comment]
@tarekabosaif Try the solution of creating the slider only when the tab is clicked.  It worked for me.
That way it won't calculate based on the height/width of the container when the page loads (which is 0 since it's hidden).

**Comment by tarekabosaif** [comment]
@atempel 
i try but it is the same problem plus it's displayed none until i click on tabs

**Comment by msypes** [comment]
Here's a solution a friend and I worked out for something with a jQueryUI accordion implementation. As was noted above, there's an issue with knowing the size the elements in the slider.
```
<script type="text/javascript">
(function($) {
    $.each(['show', 'hide'], function(i, ev) {
        var el = $.fn[ev];
        $.fn[ev] = function() {
            this.trigger(ev);
            return el.apply(this, arguments);
        };
    });
    
    $(document).ready(function () {
        $('.accordion-content').on('show', function (e) {
            window.setTimeout(function(){$('.flexslider-ws').resize();}, 0);
        });
    });
})(jQuery);
</script>
```
The first bit is just a snippet found elsewhere to define the *show* event.

The second bit does the work. The selector `.accordion-content` is the panel whose display is toggled between none and block.

In testing, `$('.flexslider-ws').resize();` worked perfectly when entered into the console, once the accordion was opened, but simply using 
```
$('.accordion-content').on('show', function (e) {
    $('.flexslider-ws').resize();
});
```
didn't. The `setTimeout` was added to see if a delay would help. It did, and after reducing the time length, we got all the way to zero. (Your mileage may vary.)
