### ISSUE TITLE
flex-active-slide class isn't always set correct

### ISSUE THREAD

**Issue by BarisW** [woocommerce/FlexSlider#193]
I have setup a synced slideshow like in this example: http://flex.madebymufffin.com/examples/thumbnail-slider.html

The slideshow contains 5 large slides and the carrousel contains 5 thumbs of 100x100 pixels. The area of the thumbs has a fixed width of 400 pixels, so the last thumb should scroll in when slide 5 is active. This works. 

However, I see some bugs with the class 'flex-active-slide' (which is added to the active thumb). 
- When slide 1 is active, the flex-active-slide is active on the 1st thumb (hurray!)
- When slide 2 is active, the flex-active-slide is still active on the 1st thumb. (booo)
- When slide 3 is active, the class jumps to thumb 3. So thumb 2 does not get the active class. 
- From the 3rd till the 5th slide, the correct thumb is set to active. 

The site isn't live so I cannot link you to it. I hope my explanation makes any sense to you. Any ideas what is causing this?

**Comment by dexterns88** [comment]
I have similar issue on version v2.6.0 on auto-slide after second item active class stay on second item.

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
