### ISSUE TITLE
Go back to Slide 0 = Broken

### ISSUE THREAD

**Issue by ar-rm** [woocommerce/FlexSlider#201]
Hi,

I can't get FlexSlider 2 to slide back to the first slide (#0) via:

$('.flexslider').flexslider(0);
or
$('.flexslider').flexanimate(0);

I've tried this right out of the box with the "demo.html" file. I just added a click() to an h3 I created just below the h2 to initiate it. I'm using FlexSlider @ 24dcdf3832.

If I set the slide number to _anything_ other than "0" it works, but as soon as I set it to "0" nothing happens.

ex:
$('.flexslider').flexslider(2); = Works
$('.flexslider').flexslider(0); = Doesn't work

Bug?

Thanks.

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
