### ISSUE TITLE
slider.count, slider.currentSlide with Multiple Sliders?

### ISSUE THREAD

**Issue by ar-rm** [woocommerce/FlexSlider#202]
Hi,

I can't seem to get "slider.count" and "slider.currentSlide" to work when there are multiple sliders on a page.

I use a class to target multiple blocks of markup to initiate flexslider() and then use your code from here http://www.woothemes.com/flexslider/ as a starting point. As much as Flexslider is supposed to be able to easily work with multiple sliders ("Maybe too easy, even"), it seems like slider.count needs some extra magic to get it to count just the slides for each slider and know which sliders is on which slide.

I tried to hook this up by modifying "demo.html" (24dcdf3) and adding the following:

``` javascript
start: function(slider) {
    $('.current-slide').text(slider.currentSlide+1);
    $('.total-slides').text(slider.count);
},
after: function(slider) {
    $('.current-slide').text(slider.currentSlide+1);
    $('.total-slides').text(slider.count);
}
```

I created the markup for .current-slide and .total-slides lower in the page.

I can't seem to figure out how to tell it to get the slider.count for just _(this)_ slider and keep the current slide number specific to each instance of Flexslider().

I have a feeling I'm just missing something, but maybe this is a feature request.

Thanks!

**Comment by shannongmclean** [comment]
@ar-rm @tylerxo I am having trouble understanding what this looks like in markup. Does anyone have an example from 2012 they could share?

**Comment by ar-rm** [comment]
This markup would work for the counter:
```
<span class="slide-position">
    <span class="current-slide"></span> of <span class="total-slides"></span>
</span>
```
If you're using the JS from @tylerxo above, it would have to be a child of the `class` or `id` that FlexSlider() is initialized on.
