### ISSUE TITLE
Touchmove (iOS) stops animation loop

### ISSUE THREAD

**Issue by rocketjoe** [woocommerce/FlexSlider#21]
After sliding on iOS (touchmove), the animation loop stops regardless pauseOnAction or animationLoop settings. After sliding left or right the animation should resume.

**Comment by briandowmobile** [comment]
On Flexslider 2 resume doesn't work.
Have to change code aboe to:

after: function(slider){ slider.pause(); slider.play(); },

and then is OK. Tested on my mobile and working.

**Comment by jeffikus** [comment]
@briandowmobile what version within the 2.x.x release versions do you mean?
