### ISSUE TITLE
Request: add mouse dragging for desktop users

### ISSUE THREAD

**Issue by matthewbuchanan** [woocommerce/FlexSlider#214]
I’ve looked at a number of sliders recently, and I really like the ones which include mouse dragging as a method of desktop navigation. Is it possible to add this to FlexSlider (would work well with its responsive features)?

**Comment by yurenlimbu** [comment]
+1

**Comment by rkakrik** [comment]
+1

**Comment by rkakrik** [comment]
Jquery.event.drag is no longer maintained. I find this library: https://github.com/mmikowski/jquery.event.ue
And similarly to example @akobashikawa:
```
if (slider.vars.drag) {
          slider.bind('udragstart.udrag', function(event) {
            event.preventDefault();
            var target = (event.px_delta_x < 0) ? slider.getTarget('next') : slider.getTarget('prev');
            slider.flexAnimate(target, slider.vars.pauseOnAction);
          });
        }
```

**Comment by nicoworq** [comment]
+1

**Comment by haxkep** [comment]
+1

**Comment by kubik101** [comment]
+1

**Comment by lauraE3** [comment]
+1

**Comment by Eiad** [comment]
+1

**Comment by piskello** [comment]
+1

**Comment by Andrijaaa98** [comment]
Is there any newer solution for draging slider? As old ones don't work for me.
