### ISSUE TITLE
"Double" scrollbar using Google Chrome

### ISSUE THREAD

**Issue by samikeijonen** [woocommerce/FlexSlider#216]
Hi.

When using latest Google Chrome (20.something) I see weird scrollbar behaviour on the right. Scrollbar is kind of "doubled" or at least it's more left that it's should be. I can see this also in Flexslider demo page.

http://flexslider.woothemes.com/

Any ideas how to fix this? It's also messing with my navigation.

**Comment by kylewhenderson** [comment]
I know this is an older post, but is there any update to this? Experiencing the exact same thing in Chrome for Windows only, but removing that line in flexslider.css doesn't seem to fix the issue any longer.
