### ISSUE TITLE
Webkit - Font Smoothing

### ISSUE THREAD

**Issue by zslabs** [woocommerce/FlexSlider#222]
Hi,
I'm noticing a different in the anti-aliasing on in Webkit for text within flex-slider. From the image (below) the top text is from a paragraph outside flex slider - and the other, inside (the lower-text is skinnier). I believe I've traced the issue down to `.flexslider .slides > li {display: none; -webkit-backface-visibility: hidden;}` The backface-visibility seems to be messing with text-rendering. I've tried a few ways to "re-add" what the rest of the site has, but no such luck as of yet. Any suggestions here? Thanks.

![Flex Slider](http://i.imgur.com/ipOVD.jpg)

**Comment by tayvano** [comment]
I doubt anyone needs this.....4 years later....but here's your solution since some clients absolutely need their font-smoothing and sliding: https://github.com/woocommerce/FlexSlider/issues/1626
