### ISSUE TITLE
Request: center thumbs if they don't span the full length available

### ISSUE THREAD

**Issue by kimlawler** [woocommerce/FlexSlider#236]
If I have only a few images in my dynamically created carousel, the thumbnails align to the left. Preferably I'd like to have the option of the thumbnails being centered in the available space.

**Comment by himmatdb** [comment]
tylerxo where should I put this code in js?

**Comment by aureshsaxena** [comment]
@himmatdb plz check flexslider documentation, you'll  get the answer

**Comment by LuxViz** [comment]
RE: CENTERING THUMBS
I tried to use the exact same JS and CSS and was not able to get this to work with my implementation. (I'm not very good with CSS and for some reason the original code did not work for me in terms of centering the thumbs within the horizontal space. )

So, I defined the ".flex-centered" class specifically to target the .flex-nav-control class, which applies the centering to the li thumbs. Then, I added one line to my JS which loads with my gallery pages. That's it!

CSS
.flex-centered li {width: 100%!important; text-align: center;}
.flex-centered li {display: inline-block!important; *display: inline!important; float: none!important;}

JS
$('.flex-control-nav').addClass('flex-centered');

**Comment by jameswilson** [comment]
The final fix for me that worked without any additional JS to dynamically add the class was this:

```
.flexslider .slides {
  text-align: center;
  width: 100% !important;
  white-space: nowrap;
}

.flexslider .slides > li {
  cursor: pointer;
  display: inline-block !important;
  *display: inline !important;
  float: none !important;
}
```

Unfortunately `!important` is required to override inline styles added via javascript to the DOM elements.
