### ISSUE TITLE
Want to display the direction navigation all the time.

### ISSUE THREAD

**Issue by jeremybarbet** [woocommerce/FlexSlider#248]
I downloaded the lastest version of Flexslider, but the direction navigation is hidden when we aren't on the slide. 
So I would display the direction navigation where I want. 

Thanks.

**Comment by Wadizorg** [comment]
.flex-direction-nav a {
        -webkit-transition: none !important;
    }

    .flex-direction-nav .flex-next {
            right: 5px !important;
    }

    .flex-direction-nav .flex-prev {
            left: 5px !important;
    }
