### ISSUE TITLE
keyboard navigation with multipley flexsliders not possible? (carousel sync)

### ISSUE THREAD

**Issue by ikoene** [woocommerce/FlexSlider#268]
While checking out carousels, I've noticed that it isn't possible to use keyboard navigation when having a setup like this:

http://flexslider.woothemes.com/thumbnail-slider.html

I think it's a really necessary feature. You should be able to address both sliders with a keyboard input, so they would stay synched.

**Comment by ardalann** [comment]
Hey guys,

This issue was resolved 2 years ago in version 2.2.0, but it still exists in 2.5.0 (demo: http://flexslider.woothemes.com/thumbnail-slider.html ) and 2.6.0 (I tested it locally). Probably one of the updates broke it again.

**Comment by jeffikus** [comment]
Will take a look in the 2.7.0 cycle.
