### ISSUE TITLE
animation:'slide'  causes "jumping image issue" on reload (only)

### ISSUE THREAD

**Issue by pirco** [woocommerce/FlexSlider#271]
I noticed when using animation:  'slide'  I get the "jumping image" problem: it shows the second image briefly before starting the slideshow proper.  but this only happens on page reload. when the page initially loads, all works great.
http://216.70.104.188/  (safari, FF and chrome on mac)

also: this might be related to the fact that the slideshow starts off stuck between image 3 and 4 on iPhone before it starts sliding with image 1...

**Comment by nikhilvm1993** [comment]
I am using angular flexslider,and iam getting images vertical, out to slider on initial load.if we close it and open again.it works fine
