### ISSUE TITLE
Occasionally the first slide is hidden, flex-viewport height is 0px

### ISSUE THREAD

**Issue by kimlawler** [woocommerce/FlexSlider#278]
I'm getting an odd bug whereby occasionally the flex-viewport div has its height set to 0px on load, and doesn't resize to fit the height of the first slide. This happens about once every.. 10 refreshes or so! 

Help?!

**Comment by verytwisty** [comment]
Thanks for posting this -  but window.load didn't work for me for some reason. 

But window.ready did! Just thought I'd share in case anyone was having the same problem.

$(window).ready(function(){
