### ISSUE TITLE
Fixed position text flicker, Safari only

### ISSUE THREAD

**Issue by mtaube** [woocommerce/FlexSlider#291]
When a flexslider animates, text in a fixed position element flickers (i.e. fixed top navbar links).

I was able to fix the flicker in most browsers by setting useCSS to false and removing the "-webkit-backface-visibility: hidden;" (see related issue [#45](https://github.com/woothemes/FlexSlider/issues/45)). Unfortunately, this does NOT solve the problem for Safari. The text still flickers!

Here's the page as it stands: (link removed)

Change the top slider and watch the navbar! In Safari, you'll notice the navbar links flicker as the slider changes. In Chrome / Firefox, the flicker is gone.

Help! The plugin has been awesome, all except for the flickering text. Thanks in advance.

**Comment by syncddesign** [comment]
Thanks @candace6b that did the trick...

**Comment by syedoz** [comment]
Thanks @mtaube you saved my life.
-webkit-backface-visibility: hidden; on the element its self did the job.

**Comment by ravik1** [comment]
implemented fixedheader.js its working fine, but in safari browser header is jittering while scrolling scroll bar from mouse ....on mac....please suggest if any solution
