### ISSUE TITLE
Touch gesturing causes slider to freeze on IOS 6

### ISSUE THREAD

**Issue by mksweet** [woocommerce/FlexSlider#345]
There is a problem with touch gesturing on IOS 6. It seems to effect the scroll-down gesture specifically. It causes the slideshow to freeze. You can’t scroll the page or slide to next/prev slides, either through gesturing or the control buttons.

Tested on Iphone4, IOS6.
Still works fine in IOS5.

Example: the issue occurs on this demo:  http://demo2.woothemes.com/?name=whitelight

I was able to temporarily fix the freezing problem by switching to Flexslide 1.8 and commenting out the section with touch gesturing. An OK stop-gap as the touch gesturing is just a nice-to-have for my site.

I tested the flexslide homepage demo and it doesn't seem to be a problem. So maybe it has something to do with full-width slides and gesturing.

Thanks for any ideas.

**Comment by channabasappa** [comment]
i have implemented flexslider in home page of below website.
https://mcmcstage.cimm2.com/

but problem is when we scroll up and down the website in iphone 5,some portion of flexslider image will be hidden automatically and if we scroll slider it works fine when page loaded. 

please refer screenshot for reference.

![scroll_up_n_down_website](https://cloud.githubusercontent.com/assets/4508107/12395341/096476ea-be27-11e5-9478-7d34060bf8f9.JPG)
![when_page_loads](https://cloud.githubusercontent.com/assets/4508107/12395342/096af862-be27-11e5-925d-01f3670473e8.JPG)

**Comment by nitinsbuzz** [comment]
Facing this problem in ios11 iphone safari. 

The problem arises soon after i scroll down a table in a fixed div with 100% height with css smooth scrolling. 

I have two slides where the 2nd is a very large table with native horizontal scrolling.

Problem: Iphone touch freezes completely for a number of seconds.

It looks like an event handler is getting stuck in a while loop.
