### ISSUE TITLE
How to Stop the Flexsilder when the Youtube Video is Playing.

### ISSUE THREAD

**Issue by keneater** [woocommerce/FlexSlider#346]
I cant find any information on this one.
This is my site. 
http://spyking.org

After the video is played on the main page the Slider still moves and Slides, How do i fix this?

**Comment by telemarker** [comment]
check out this thread for html5 video solution:
https://github.com/woothemes/FlexSlider/issues/1286

**Comment by adalbertohofmanns** [comment]
i just changed 0 to 1 on playVideoAndPauseOthers($('.ctv-directors-frame iframe')[1]);

like below

before: function(slider){
	        if (slider.slides.eq(slider.currentSlide).find('iframe').length !== 0)
	           $f( slider.slides.eq(slider.currentSlide).find('iframe').attr('id') ).api('pause');
	           /* ------------------  YOUTUBE FOR AUTOSLIDER ------------------ */
	           playVideoAndPauseOthers($('.ctv-directors-frame iframe')[1]);
	    }

**Comment by adalbertohofmanns** [comment]
jQuery(window).load(function() {
	var Projeto = {};

	var vimeoPlayers = jQuery('.flexslider').find('iframe'), player;

	for (var i = 0, length = vimeoPlayers.length; i < length; i++) {
	        player = vimeoPlayers[i];
	        $f(player).addEvent('ready', ready);
	}

	function addEvent(element, eventName, callback) {
	    if (element.addEventListener) {
	        element.addEventListener(eventName, callback, false)
	    } else {
	        element.attachEvent(eventName, callback, false);
	    }
	}

	function ready(player_id) {
	    var froogaloop = $f(player_id);
	    froogaloop.addEvent('play', function(data) {
	     jQuery('.flexslider').flexslider("pause");
	    });

	    froogaloop.addEvent('pause', function(data) {
	        jQuery('.flexslider').flexslider("play");
	    });
	}

	jQuery(".flexslider")

	.flexslider({
	    animation: "fade",
	    easing: "swing",
	    keyboard: true,
	    slideshow: true,
	   	controlNav: false,
	    directionNav: true,
	    animationLoop: true,
	    touch: false,
	    video: true,
	    initDelay: 500,
	    pauseOnHover: true, 
	    animationSpeed: 765,
	    smoothHeight: false,
	    before: function(slider){
	        if (slider.slides.eq(slider.currentSlide).find('iframe').length !== 0)
	           $f( slider.slides.eq(slider.currentSlide).find('iframe').attr('id')  ).api('pause');
	           /* ------------------  YOUTUBE FOR AUTOSLIDER ------------------ */
	           playVideoAndPauseOthers($('.ctv-directors-frame iframe')[1]);
	    }


	});

	function playVideoAndPauseOthers(frame) {
		$('iframe').each(function(i) {
			var func = this === frame ? 'playVideo' : 'stopVideo';
			this.contentWindow.postMessage('{"event":"command","func":"' + func + '","args":""}', '*');
		});
	}

	/* ------------------ PREV & NEXT BUTTON FOR FLEXSLIDER (YOUTUBE) ------------------ */
	$('.flex-next, .flex-prev').click(function() {
		playVideoAndPauseOthers($('.ctv-directors-frame iframe')[0]);
	});


});

**Comment by voodoomotion** [comment]
Hi Guys,

Well done for solving this but i can't get this working with vimeo :'( .. I need to slide from one video to the next but the previous video continues playing.

Desperate to get my student showreel website running soon.  Please can somebody post the entire HTML or a example project?

Much appreciated in advance!

**Comment by psanjib** [comment]
@Duppi, i have tried with vimeo and youtube it works fine. it save a lot time.

thanks

**Comment by Duppi** [comment]
@psanjib you welcom
