### ISSUE TITLE
FlexSlider navigation issue in Chrome 22 [Win 7]

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/FlexSlider#351]
Hi guys, does anybody noticed Flex slider not working properly in new Google Chrome 22? 

Just reporting: navigation elements are not working. Completely. They are being displayed but nothing happens when clicked. CSS hovers styles works fine on those.

I have noticed some other (not Flex slider related) CSS errors with Chrome 22 so it might be some bug inside the browser, not your code as the slider works fine in other browsers. As I said, just reporting.

**Comment by SeanKendle** [comment]
You still have v2.0 on your demo website.  I would highly recommend you move to v2.2+ if this issue is fixed, as I am still unable to use the navigation buttons in FF 35.0 and Chrome 39.0.2171.95 m
