### ISSUE TITLE
Arrows in Internet Explorer

### ISSUE THREAD

**Issue by mattyza** [woocommerce/FlexSlider#441]
Reported via e-mail in the WooThemes mailbag:

"Hi
I noticed that in IE, the nav arrows were appearing on the outside of the frame and popping into the correct position on hover. 

Please note that I was using the IE Tab 2 plugin for Firefox (which seems to use an older version of IE than installed))when I was testing this so I am not sure if the bug would actually show up in IE7 or IE8 as I only have IE9 installed and it works fine.

In any case, I found this tweak to the CSS provided a solution:

.flex-direction-nav .flex-next {
background-position: 100% 0;
right: -36px;
display: none; /_added_/
}

.flex-direction-nav .flex-prev {
left: -36px;
display: none; /_added_/
}

.flexslider:hover .flex-next {
opacity: 0.8;
right: 15px;
display: block; /_added_/
}

.flexslider:hover .flex-prev {
opacity: 0.8;
left: 15px;
display: block; /_added_/
}

Hope this is useful to you and thanks for a great slider!"

**Comment by shrinehi** [comment]
thanks mattyza
worked for me. validated on IE8, IE9
