### ISSUE TITLE
"Cover flow" style carousel image switching

### ISSUE THREAD

**Issue by sergesav** [woocommerce/FlexSlider#523]
Hello. 
First of all, thanks for the great plugin!
I am currently trying to implement the so-called cover flow style image carousel and would like to ask for some help. The layout I'm aiming for is similar to this one (http://bit.ly/VbKYmf), although I'd like to have only 3 images visible at a time -- the main one, the previous and the next one (on the sides). Please assist me in determining which  template to modify (the basic slider or the basic carousel) and where should I start.

Thank you.

Serge

**Comment by HandHugs** [comment]
Did you ever figure this out?
