### ISSUE TITLE
touch - swipe is way to sensistive

### ISSUE THREAD

**Issue by knalleDK** [woocommerce/FlexSlider#530]
on iOS:

it's almost impossible to scroll down without accidentally triggering a horizontal swipe ( = slides to next or previous image).

Any way of disabling triggering the sliding animation (next/prev) when I'm actually scrolling the page?

AND perhaps lowering the sensistivity - so it won't trigger slide animation if i have only swiped 5 pixels or so??

**Comment by haliphax** [comment]
Was this code never incorporated? I'm using the latest version, and it still has this issue where vertical swipes are captured by the slideshow (even though the slideDirection is "horizontal") and, if a slideshow takes up too much of the viewport, you get stuck, unable to scroll anywhere.
