### ISSUE TITLE
GPL License Question

### ISSUE THREAD

**Issue by aphillipo** [woocommerce/FlexSlider#559]
Hi Guys,

Just want to make certain I'm complying with the law and the spirit of your license.

I intend to reference your library Flexslider in my commercial project.  I want to be able to use it because it looks like the one of the best implementations I have seen.  However, I will not be releasing any frontend (or for that matter backend) code from this project anytime soon, as the timescales are so very tight.

As long as I just reference it as a separate file and do not compile it into my code base (either through minification or otherwise), is this breaking the rules or the spirit in which you give us this great library?

Thanks in advance,

Andy.

**Comment by neil-119** [comment]
http://greendrake.info/#nfy0

> Because your code will run in the same process with the GPL library, reference its components (with or without modification), and share data structures with them, your code will be considered a derivative work and so it will need to be GPL'ed too.

This makes the library literally unusable in a modern commercial application that's built on top of front-end frameworks with webpack / minification etc. So sad to see.
