### ISSUE TITLE
Animation "fade" fires navigation buttons

### ISSUE THREAD

**Issue by Sandrilyon** [woocommerce/FlexSlider#641]
Hello! I've an issue with slider using animation effect "fade". This effect applies not only for images in the slider, but also for my navigation buttons. It looks when first images fades out and the second fades in, the same thing touches the nav buttons as well. They blink after each slider change. In the demo example fade effect works well. 

How to fix it?

**Comment by emilyljohnson** [comment]
Thank you for this! Deleting `smoothHeight: true` fixed an issue I was having where the control nav was blinking with each fade effect.
