### ISSUE TITLE
reinitialize/refresh/update flexslider

### ISSUE THREAD

**Issue by mhesabi** [woocommerce/FlexSlider#642]
hey, I have two layout mode to show my blog posts. one is `list view` and another is `grid view` and this will be done by clicking on a button.
The problem is after switch layouts slide sizes should update. any idea how to do it?

**Comment by BDhara** [comment]
M having doubt plz help...
when m resizing my window images looks very small

**Comment by erickao5566** [comment]
> oh, ignore me.
> I reached my goal by doing `$('.flex-active-slide').resize();`
> 
> I'm really sorry...

its work for me, thks
