### ISSUE TITLE
Carousel Nav / Sync'd slider not working past 1st slide

### ISSUE THREAD

**Issue by ac23** [woocommerce/FlexSlider#693]
I'm currently using two sliders - the first an html slider that rotates out divs (with background images set and items overlaid) and the second a carousel slider of icons sync'd to the main slider. (see here: http://stuffimmaking.com/de)

If I don't set a min/max items and have all the items show, the active class is only added to the carousel when on the first and second slide. After that the main slideshow continues to move along, but the carousel does not. In addition, once the slideshow moves to the second slide, the carousel navigation becomes useless and does nothing -- but if you click around the icon navigation prior to the first slide transition then the slider switches like you would expect it to.

Now this only seems to be an issue when the slider is actually set to slideshow. If it isn't, you can click each icon and the slider will move along correctly and active classes will be applied, but the functionality I really need is for it to rotate through correctly, staying in sync and still functioning as links to control the lead slider.

This occurs with both 2.1 and the 2.2 beta.

Any help would be appreciated. 

`<script type="text/javascript">
jQuery(document).ready(function($) {
$('#carousel').flexslider({
animation: "slide",
controlNav: false,
directionNav: false,
slideshow: true,
itemWidth: 94,
itemMargin: 10,
asNavFor: '#slider'
});
$('#slider').flexslider({
animation: "slide",
controlNav: false,
slideshow: true,
slideshowSpeed: 5000,
directionNav: false,
selector: ".slides > .slide",
sync: "#carousel"
});
});
</script>`

**Comment by zanderi** [comment]
This is still an issue it appears the class active is not added to the carousel and opacity is left at 0 for each slide in the carousel. I have created a fiddle here https://jsfiddle.net/zanderi/o0z2fabd/1/
