### ISSUE TITLE
How to use start callback outside flexslider.js

### ISSUE THREAD

**Issue by fleduc** [woocommerce/FlexSlider#789]
Could anyone tell me how to use the start callback outside flexslider.js.

I want to execute a function right after the slider is initialize but I don't want to put my code inside the pluggin file since it might be updated some day and I would loose my modifications...

I know that is should be place in the $(document).ready section but I don't remember how.

Thanks.

**Comment by carolineschnapp** [comment]
I cannot find that 'Advanced' tab.
