### ISSUE TITLE
Flickering and jumping behavior when using animation:"slide"

### ISSUE THREAD

**Issue by ghost** [woocommerce/FlexSlider#820]
I just installed Flexslider on the following mobile site: http://planocycling.com/m

Thanks for this plugin.

You'll notice that there is a flickering/jumping behavior when the page loads. It happens in Chrome, Firefox and Safari and is even more noticeable on the iPhone (and possibly other mobile devices) because the actual height of the slider area expands when it flickers. Obviously it's not a huge deal but it would be nice if I could eliminate the flicker. Switching to animation:"fade" resolves the problem so it has something to do with the animation type. I've tried all the remedies I've seen in the forums for similar problems, but no luck.

Any help is greatly appreciated.

**Comment by DannyFeliz** [comment]
+1

**Comment by rzrz** [comment]
+1

**Comment by developwitheddy** [comment]
I am running into the same problem on my WordPress site. Why is this issue closed?

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
