### ISSUE TITLE
Flashing white when initiating FlexSlider after image load

### ISSUE THREAD

**Issue by patrikelfstrom** [woocommerce/FlexSlider#848]
If you initiate FlexSlider with the fade animation after page load when images are visible. FlexSlider will set the opacity on the first image to 0 and then fade it in.
This will cause a "flashing" which is quite ugly.

A solution:
On row 893 replace: 

``` javascript
slider.slides.css({ "opacity": 0, "display": "block", "zIndex": 1 }).eq(slider.currentSlide).css({"zIndex": 2}).animate({"opacity": 1},slider.vars.animationSpeed,slider.vars.easing);
```

With: 

``` javascript
var currentSlide = slider.slides.css({ "opacity": 0, "display": "block", "zIndex": 1 }).eq(slider.currentSlide);

if(currentSlide.is(':visible')) {
    currentSlide.css({"opacity": 1, "zIndex": 2});
} else {
    currentSlide.css({"zIndex": 2}).animate({"opacity": 1},slider.vars.animationSpeed,slider.vars.easing);
}
```

This checks if the slide is visible or not and does nothing if it is visible and fades the image in if it's not visible.

This might not be the correct way to fix it but it fixed the error for me.
If someone has a better solution, please share.

**Comment by iantbarker** [comment]
@jst This is old, but the `fadeFirstSlide` option is not documented. It took me a while to find this issue only to realize the fix already exists :-)

**Comment by Pirena01** [comment]
I followed vmasto's solution but changed the css to 
.flexslider.loading .slides  { opacity: 0 !important; }
that worked for me.
