### ISSUE TITLE
Issue on the first thumbnail when slideshow: true and animationLoop: true

### ISSUE THREAD

**Issue by Kash121** [woocommerce/FlexSlider#852]
Hi,

I am trying to implement an auto scroll slider with play/pause buttons. When the slider reaches the last slide i want it to go to the first slide after the last one. However only the  slider contents are refreshed but focus does not go to the first thumbnail and the thumbnails are in sync only after the slider has reached the 3rd slide.

Here is my code:

```
  $(window).load(function () {
     $('#carousel').flexslider({
         animation: "slide",
         controlNav: false,
         animationLoop: false,
         slideshow: false,
         itemWidth: 110,
         itemMargin: 4,
         allowOneSlide: false,
         asNavFor: '#slider'
     });

     $('#slider').flexslider({
         animation: "fade",
         controlNav: false,
         directionNav: false,
         slideshowSpeed: 8000,
         animationSpeed: 1000,
         animationLoop: true,
         pausePlay: true,
         slideshow: true,
         keyboard: true,
         sync: "#carousel",
         start: function (slider) {
             $('body').removeClass('loading');                
         }
     });
 });
```

Please suggest the resolution for this issue.

**Comment by vinaymcscet** [comment]
how can i use this code and where i can write in above functions,please tell us with example.
if (Math.ceil((target + 1)/slider.visible) - 1 !== slider.currentSlide) {
