### ISSUE TITLE
FlexSlider breaks iframe videos in Safari...

### ISSUE THREAD

**Issue by patrickowtf** [woocommerce/FlexSlider#88]
I was initially trying to put an embedded vimeo video inside the slider, along with other images. That was working great EXCEPT for in Safari. In Safari, the video breaks. Sometimes it doesn't even show up, but the audio still works. Also the controls become unresponsive. 

I did some troubleshooting and ended up with a slider full of images and an iframe embedded video right next to it. The video was not inside the slider. When I initialized the slider, the iframe breaks. If I remove the initialization, the iframe video works perfectly. 

Keep in mind this is only in safari. Just the fact that there is a FlexSlider somewhere on the page is breaking the iframe.

**Comment by shaikriyaz** [comment]
mp4 video can't open in safari ,i use to iframe but open the all browsers, not ope the video in safari browser please salve the problem
