### ISSUE TITLE
min/max Items and fade animation

### ISSUE THREAD

**Issue by shipleyr** [woocommerce/FlexSlider#923]
These do not appear to be working together. I have a flexslider setup with 12 items, I want the animation to be a fade effect but I'd like 4 items visible at one time.

When I set the animation property to fade only one item gets displayed, when I use slide it displays 4. My expectation was that it would do a fade replacement of the 4 visible items with the next 4 in the set.

**Comment by shipleyr** [comment]
@jeffikus Is this fixed?

**Comment by jeffikus** [comment]
Hi @shipleyr - have you tried with the latest version? https://github.com/woothemes/FlexSlider/releases/latest

**Comment by shipleyr** [comment]
@jeffikus It's taken some time to get to a position to test this but no... it doesn't work with the new release. It works if you setup a slider with the animation as slide but fading with min/max items set gets ignored... it only shows one item.

**Comment by sunilkjt** [comment]
its still not fixed am having safe issue.
