### ISSUE TITLE
Images won't load on first page load

### ISSUE THREAD

**Issue by benbarry** [woocommerce/FlexSlider#97]
I am not much of a programmer, but I don't see anything obvious going wrong here. I can repro every time by opening this page in a Google Chrome incognito window:

http://www.designforfun.com/index.php?id=79

If I click the next / back arrows on the flexslider it snaps into place and starts working. If I close this project and open another, or navigate away and back it all works fine.

**Comment by dabeer88** [comment]
Hi mbmufffin,

I am newbie, I have a problem in flexslider, Initially it is showing all the slides and after loading it is showing the slider, which is annoying in the site.

Please help me to solve the problem.

Reference(Wait for home page to load after welcome page) : http://www.forbesmiddleeast.com/

Thanks in Advance!

**Comment by sdaponte** [comment]
@dabeer88 - I have run into this issue on many of our sites and have not found a programatic solution.
What we tend to do is set a max height on our slider container with CSS, and give it a overflow of hidden. That way while it's loading all the images on top of each other it will not break the overall layout.
You could also hide the slider and make it display on the end callback. Hope this helps!
