### ISSUE TITLE
Double Cloning on animation: "slide"

### ISSUE THREAD

**Issue by seansean11** [woocommerce/FlexSlider#975]
I noticed that when I set the slider to animation: "slide" that my last slide was showing up first (on document ready).  After investigating this and testing it out on an isolated case, it seems as though it may be a bug.  When the carousel is set to slide animation and the animationLoop at its default, true, the plugin appends 2 copies of the first slide and prepends 2 copies of the last slide.  The first prepended copy is display block, showing the last slide in front of the first.

I believe the bug must have started when the plugin was modified to include aria-role="hidden" on the cloned slides.  The following code is what is causing the issue:

``` javascript
if (type !== "init") slider.container.find('.clone').remove();
          slider.container.append(slider.slides.first().clone().addClass('clone').attr('aria-hidden', 'true')).prepend(slider.slides.last().clone().addClass('clone').attr('aria-hidden', 'true'));
                      methods.uniqueID( slider.slides.first().clone().addClass('clone') ).appendTo( slider.container );
                      methods.uniqueID( slider.slides.last().clone().addClass('clone') ).prependTo( slider.container );
```

I have removed these 2 lines to delete the duplication:

``` javascript
methods.uniqueID( slider.slides.first().clone().addClass('clone') ).appendTo( slider.container );
methods.uniqueID( slider.slides.last().clone().addClass('clone') ).prependTo( slider.container );
```

This allows me to keep the clones with aria-role="hidden" for screen readers and delete the buggy duplicates.  Maybe you could fill me in further about this.

**Comment by bansay** [comment]
WOW. Thanks y'all. This was really bugging me, I didn't know why .flexslider was double cloning the first and last, and starting on the 2nd slide. This fixed the flexslider double clone for me too. Cheers!

**Comment by miloche1701** [comment]
i have the exact same issue : on animation 'slide' the first slide is duplicated. 
Unfortunately my version of flexslider v2.2.2, this line is already removed... so I have no idea of what to do to fix this. (I'm using jQuery 1.11.1)...

**Comment by Interactive** [comment]
I am having this same issue, when removing the line

slider.container.append(slider.slides.first().clone().addClass('clone').attr('aria-hidden', 'true')).prepend(slider.slides.last().clone().addClass('clone').attr('aria-hidden', 'true'));

It creates a whole separate issue. The first slide basically shows for a short second and then moves to the rest of the slides but at the end returning a blank slide a the beginning of the loop never seeing the first slide again.

I and using v 2.2.0 and even updating to v2.5.0 does not change it.
