### ISSUE TITLE
slider with "slide" animation type causing overflow

### ISSUE THREAD

**Issue by jennoster** [woocommerce/FlexSlider#98]
Hi -

I'm trying to use the flexslider script on a mobile browser app. The issue I'm having is with a slider that's supposed to extend across the entire width of the window, so I have the image width set to 100%. It looks like the overflow is coming from the ul class="slides" which has a generated width of 1200%. While the overlow doesn't result in a horizontal scroll bar, it does show if the user swipes the page left or right while using the app, which isn't ideal. 

I should mention that this issue doesn't happen when the animation type is set to "fade."

Any insite would be helpful!

**Comment by carlitoshxcx** [comment]
Thank you @adikwr again, you give me a huge help!

**Comment by dipesh-spinx** [comment]
Worked for me too. thanks a lot !!
