### ISSUE TITLE
FlexSlider doesn't properly reduce in size when used as part of a table layout

### ISSUE THREAD

**Issue by lenscraft** [woocommerce/FlexSlider#980]
When FlexSlider is in a table layout, the size doesn't reduce when the parent table-cell reduces in width.  (It does increase in size when the parent cell gets wider, but never gets narrower.)

**Comment by PCandtheWeb** [comment]
I had the same issue. Is there a fix for this?

**Comment by jeffikus** [comment]
@PCandtheWeb @lenscraft  do you have live examples of this?

**Comment by PCandtheWeb** [comment]
Hi @jeffikus,

Thanks for the reply.  Here is a bare bones example of a flexslider not resizing when inside of a table layout...http://patrickcicere.com/flexslider/flexslider-table.html

**Comment by jeffikus** [comment]
Thanks! I'll take a look!

**Comment by PCandtheWeb** [comment]
Hi @jeffikus and @lenscraft,

After looking into this issue further, I believe it can be fixed by adding a table-layout: fixed to the table element that contains the flexslider.

**Comment by mine-t** [comment]
Hello.
I found this hack.

```css
.flexgrid {
  box-sizing: border-box;
  margin-right: -99999px;
}
```

**Comment by mine-t** [comment]
sorry mistake.

.flexgrid  =>  .flexslider
